{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Training Session"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2018-07-11T14:53:49.219043Z",
     "start_time": "2018-07-11T14:53:48.971119Z"
    },
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "import pickle\n",
    "\n",
    "from build_vocab import *\n",
    "from build_answers import *\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2018-07-11T14:53:49.235056Z",
     "start_time": "2018-07-11T14:53:49.220832Z"
    },
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "# train2014\n",
    "answers_path = '/home/ubuntu/dotCuda/notebook/answers.pkl'\n",
    "with open(answers_path, 'rb') as f:\n",
    "    answers = pickle.load(f)\n",
    "\n",
    "vocab_path = '../../dotCuda/notebook/vocab.pkl'\n",
    "with open(vocab_path, 'rb') as f:\n",
    "    vocab = pickle.load(f)\n",
    "    \n",
    "# val2014\n",
    "answers_path = '/home/ubuntu/dotCuda/notebook/valanswers.pkl'\n",
    "with open(answers_path, 'rb') as f:\n",
    "    valanswers = pickle.load(f)\n",
    "\n",
    "vocab_path = '../../dotCuda/notebook/valvocab.pkl'\n",
    "with open(vocab_path, 'rb') as f:\n",
    "    valvocab = pickle.load(f)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2018-07-11T14:54:10.272053Z",
     "start_time": "2018-07-11T14:53:49.236948Z"
    }
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "loading VQA annotations and questions into memory...\n",
      "0:00:07.412888\n",
      "creating index...\n",
      "index created!\n",
      "loading VQA annotations and questions into memory...\n",
      "0:00:08.230801\n",
      "creating index...\n",
      "index created!\n"
     ]
    }
   ],
   "source": [
    "from dataset import *\n",
    "\n",
    "train_dataset = COCODataset(vocab=vocab, answers=answers)\n",
    "val_dataset = COCODataset(vocab=valvocab, answers=valanswers)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "ExecuteTime": {
     "end_time": "2018-07-10T12:30:16.457121Z",
     "start_time": "2018-07-10T12:30:16.454260Z"
    }
   },
   "source": [
    "### Network Model"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2018-07-11T14:54:10.278392Z",
     "start_time": "2018-07-11T14:54:10.273843Z"
    },
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "# import network \n",
    "from network_v5 import *"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2018-07-11T14:54:16.018908Z",
     "start_time": "2018-07-11T14:54:10.280034Z"
    },
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "import torch\n",
    "device = torch.device('cuda')\n",
    "\n",
    "vocab_size = len(vocab)\n",
    "model = ConcatNet(vocab_size).to(device)\n",
    "\n",
    "#state_dict = torch.load('model_epoch4.pt')\n",
    "#model.load_state_dict(state_dict)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Trainer Class"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2018-07-11T14:54:16.174603Z",
     "start_time": "2018-07-11T14:54:16.020741Z"
    },
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "# import trainer\n",
    "from trainer import VQATrainer\n",
    "\n",
    "trainer = VQATrainer(model, device)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Train!"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2018-07-11T14:59:12.611470Z",
     "start_time": "2018-07-11T14:56:06.871989Z"
    }
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 0 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.04946 and accuracy 0.000 in 0.6477s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.05019 and accuracy 0.000 in 0.6472s\n",
      "Epoch 1 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.04808 and accuracy 0.000 in 0.6806s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.05015 and accuracy 0.000 in 0.6161s\n",
      "Epoch 2 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.05132 and accuracy 0.000 in 0.6948s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.05013 and accuracy 0.000 in 0.6152s\n",
      "Epoch 3 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.04842 and accuracy 0.000 in 0.6808s\n",
      "  Validating...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7fa903916c50>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/site-packages/torch/utils/data/dataloader.py\", line 349, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/site-packages/torch/utils/data/dataloader.py\", line 328, in _shutdown_workers\n",
      "    self.worker_result_queue.get()\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/queues.py\", line 337, in get\n",
      "    return _ForkingPickler.loads(res)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/site-packages/torch/multiprocessing/reductions.py\", line 70, in rebuild_storage_fd\n",
      "    fd = df.detach()\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/resource_sharer.py\", line 57, in detach\n",
      "    with _resource_sharer.get_connection(self._id) as conn:\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/resource_sharer.py\", line 87, in get_connection\n",
      "    c = Client(address, authkey=process.current_process().authkey)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 493, in Client\n",
      "    answer_challenge(c, authkey)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 732, in answer_challenge\n",
      "    message = connection.recv_bytes(256)         # reject large message\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 216, in recv_bytes\n",
      "    buf = self._recv_bytes(maxlength)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 407, in _recv_bytes\n",
      "    buf = self._recv(4)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 383, in _recv\n",
      "    raise EOFError\n",
      "EOFError: \n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "   >> Epoch finished with loss 64.05012 and accuracy 0.000 in 0.4984s\n",
      "Epoch 4 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.05336 and accuracy 0.000 in 0.6370s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.05013 and accuracy 0.000 in 0.6246s\n",
      "Epoch 5 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.04667 and accuracy 0.000 in 0.6502s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.05013 and accuracy 0.000 in 0.6062s\n",
      "Epoch 6 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.04759 and accuracy 0.000 in 0.6392s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.05014 and accuracy 0.000 in 0.6187s\n",
      "Epoch 7 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.04559 and accuracy 0.000 in 0.6517s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.05016 and accuracy 0.000 in 0.6106s\n",
      "Epoch 8 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.05062 and accuracy 0.000 in 0.6362s\n",
      "  Validating...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7fa90395a4e0>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/site-packages/torch/utils/data/dataloader.py\", line 349, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/site-packages/torch/utils/data/dataloader.py\", line 328, in _shutdown_workers\n",
      "    self.worker_result_queue.get()\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/queues.py\", line 337, in get\n",
      "    return _ForkingPickler.loads(res)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/site-packages/torch/multiprocessing/reductions.py\", line 70, in rebuild_storage_fd\n",
      "    fd = df.detach()\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/resource_sharer.py\", line 57, in detach\n",
      "    with _resource_sharer.get_connection(self._id) as conn:\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/resource_sharer.py\", line 87, in get_connection\n",
      "    c = Client(address, authkey=process.current_process().authkey)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 493, in Client\n",
      "    answer_challenge(c, authkey)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 732, in answer_challenge\n",
      "    message = connection.recv_bytes(256)         # reject large message\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 216, in recv_bytes\n",
      "    buf = self._recv_bytes(maxlength)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 407, in _recv_bytes\n",
      "    buf = self._recv(4)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 383, in _recv\n",
      "    raise EOFError\n",
      "EOFError: \n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "   >> Epoch finished with loss 64.05016 and accuracy 0.000 in 0.4995s\n",
      "Epoch 9 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.04562 and accuracy 0.000 in 0.6818s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.05017 and accuracy 0.000 in 0.6346s\n",
      "Epoch 10 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.04855 and accuracy 0.000 in 0.7159s\n",
      "  Validating...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7fa90395a4e0>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/site-packages/torch/utils/data/dataloader.py\", line 349, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/site-packages/torch/utils/data/dataloader.py\", line 328, in _shutdown_workers\n",
      "    self.worker_result_queue.get()\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/queues.py\", line 337, in get\n",
      "    return _ForkingPickler.loads(res)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/site-packages/torch/multiprocessing/reductions.py\", line 70, in rebuild_storage_fd\n",
      "    fd = df.detach()\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/resource_sharer.py\", line 57, in detach\n",
      "    with _resource_sharer.get_connection(self._id) as conn:\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/resource_sharer.py\", line 87, in get_connection\n",
      "    c = Client(address, authkey=process.current_process().authkey)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 493, in Client\n",
      "    answer_challenge(c, authkey)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 732, in answer_challenge\n",
      "    message = connection.recv_bytes(256)         # reject large message\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 216, in recv_bytes\n",
      "    buf = self._recv_bytes(maxlength)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 407, in _recv_bytes\n",
      "    buf = self._recv(4)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 383, in _recv\n",
      "    raise EOFError\n",
      "EOFError: \n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "   >> Epoch finished with loss 64.05020 and accuracy 0.000 in 0.4709s\n",
      "Epoch 11 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.05029 and accuracy 0.000 in 0.6318s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.05024 and accuracy 0.000 in 0.6648s\n",
      "Epoch 12 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.05133 and accuracy 0.000 in 0.6349s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.05027 and accuracy 0.000 in 0.6237s\n",
      "Epoch 13 of 100\n",
      "  Training...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7fa903a113c8>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/site-packages/torch/utils/data/dataloader.py\", line 349, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/site-packages/torch/utils/data/dataloader.py\", line 328, in _shutdown_workers\n",
      "    self.worker_result_queue.get()\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/queues.py\", line 337, in get\n",
      "    return _ForkingPickler.loads(res)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/site-packages/torch/multiprocessing/reductions.py\", line 70, in rebuild_storage_fd\n",
      "    fd = df.detach()\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/resource_sharer.py\", line 57, in detach\n",
      "    with _resource_sharer.get_connection(self._id) as conn:\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/resource_sharer.py\", line 87, in get_connection\n",
      "    c = Client(address, authkey=process.current_process().authkey)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 493, in Client\n",
      "    answer_challenge(c, authkey)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 732, in answer_challenge\n",
      "    message = connection.recv_bytes(256)         # reject large message\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 216, in recv_bytes\n",
      "    buf = self._recv_bytes(maxlength)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 407, in _recv_bytes\n",
      "    buf = self._recv(4)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 383, in _recv\n",
      "    raise EOFError\n",
      "EOFError: \n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "    ....iteration 1/55470\r",
      "   >> Epoch finished with loss 64.04574 and accuracy 0.000 in 0.5335s\n",
      "  Validating...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7fa903a113c8>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/site-packages/torch/utils/data/dataloader.py\", line 349, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/site-packages/torch/utils/data/dataloader.py\", line 328, in _shutdown_workers\n",
      "    self.worker_result_queue.get()\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/queues.py\", line 337, in get\n",
      "    return _ForkingPickler.loads(res)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/site-packages/torch/multiprocessing/reductions.py\", line 70, in rebuild_storage_fd\n",
      "    fd = df.detach()\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/resource_sharer.py\", line 57, in detach\n",
      "    with _resource_sharer.get_connection(self._id) as conn:\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/resource_sharer.py\", line 87, in get_connection\n",
      "    c = Client(address, authkey=process.current_process().authkey)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 493, in Client\n",
      "    answer_challenge(c, authkey)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 732, in answer_challenge\n",
      "    message = connection.recv_bytes(256)         # reject large message\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 216, in recv_bytes\n",
      "    buf = self._recv_bytes(maxlength)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 407, in _recv_bytes\n",
      "    buf = self._recv(4)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 383, in _recv\n",
      "    raise EOFError\n",
      "EOFError: \n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "    ....iteration 1/55470\r",
      "   >> Epoch finished with loss 64.05031 and accuracy 0.000 in 0.5031s\n",
      "Epoch 14 of 100\n",
      "  Training...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7fa903a113c8>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/site-packages/torch/utils/data/dataloader.py\", line 349, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/site-packages/torch/utils/data/dataloader.py\", line 328, in _shutdown_workers\n",
      "    self.worker_result_queue.get()\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/queues.py\", line 337, in get\n",
      "    return _ForkingPickler.loads(res)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/site-packages/torch/multiprocessing/reductions.py\", line 70, in rebuild_storage_fd\n",
      "    fd = df.detach()\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/resource_sharer.py\", line 57, in detach\n",
      "    with _resource_sharer.get_connection(self._id) as conn:\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/resource_sharer.py\", line 87, in get_connection\n",
      "    c = Client(address, authkey=process.current_process().authkey)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 493, in Client\n",
      "    answer_challenge(c, authkey)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 732, in answer_challenge\n",
      "    message = connection.recv_bytes(256)         # reject large message\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 216, in recv_bytes\n",
      "    buf = self._recv_bytes(maxlength)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 407, in _recv_bytes\n",
      "    buf = self._recv(4)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 383, in _recv\n",
      "    raise EOFError\n",
      "EOFError: \n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "   >> Epoch finished with loss 64.04617 and accuracy 0.000 in 0.5299s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.05033 and accuracy 0.000 in 0.6379s\n",
      "Epoch 15 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.05161 and accuracy 0.000 in 0.6371s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.05034 and accuracy 0.000 in 0.6509s\n",
      "Epoch 16 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.04893 and accuracy 0.000 in 0.6570s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.05036 and accuracy 0.000 in 0.6043s\n",
      "Epoch 17 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.04795 and accuracy 0.000 in 0.6244s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.05038 and accuracy 0.000 in 0.6100s\n",
      "Epoch 18 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.05183 and accuracy 0.000 in 0.6461s\n",
      "  Validating...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7fa903a113c8>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/site-packages/torch/utils/data/dataloader.py\", line 349, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/site-packages/torch/utils/data/dataloader.py\", line 328, in _shutdown_workers\n",
      "    self.worker_result_queue.get()\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/queues.py\", line 337, in get\n",
      "    return _ForkingPickler.loads(res)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/site-packages/torch/multiprocessing/reductions.py\", line 70, in rebuild_storage_fd\n",
      "    fd = df.detach()\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/resource_sharer.py\", line 57, in detach\n",
      "    with _resource_sharer.get_connection(self._id) as conn:\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/resource_sharer.py\", line 87, in get_connection\n",
      "    c = Client(address, authkey=process.current_process().authkey)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 493, in Client\n",
      "    answer_challenge(c, authkey)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 732, in answer_challenge\n",
      "    message = connection.recv_bytes(256)         # reject large message\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 216, in recv_bytes\n",
      "    buf = self._recv_bytes(maxlength)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 407, in _recv_bytes\n",
      "    buf = self._recv(4)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 383, in _recv\n",
      "    raise EOFError\n",
      "EOFError: \n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "   >> Epoch finished with loss 64.05038 and accuracy 0.000 in 0.4998s\n",
      "Epoch 19 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.04798 and accuracy 0.000 in 0.6706s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.05038 and accuracy 0.000 in 0.5942s\n",
      "Epoch 20 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.04942 and accuracy 0.000 in 0.6344s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.05037 and accuracy 0.000 in 0.6266s\n",
      "Epoch 21 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.04736 and accuracy 0.000 in 0.6472s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.05037 and accuracy 0.000 in 0.6579s\n",
      "Epoch 22 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.04658 and accuracy 0.000 in 0.6548s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.05038 and accuracy 0.000 in 0.6213s\n",
      "Epoch 23 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.04572 and accuracy 0.000 in 0.6314s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.05039 and accuracy 0.000 in 0.6174s\n",
      "Epoch 24 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.04613 and accuracy 0.000 in 0.6462s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.05039 and accuracy 0.000 in 0.6285s\n",
      "Epoch 25 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.04697 and accuracy 0.000 in 0.6476s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.05041 and accuracy 0.000 in 0.6258s\n",
      "Epoch 26 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.04821 and accuracy 0.000 in 0.6300s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.05040 and accuracy 0.000 in 0.6054s\n",
      "Epoch 27 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.04826 and accuracy 0.000 in 0.6638s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.05042 and accuracy 0.000 in 0.6454s\n",
      "Epoch 28 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.04490 and accuracy 0.000 in 0.6370s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.05040 and accuracy 0.000 in 0.6413s\n",
      "Epoch 29 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.04671 and accuracy 0.000 in 0.6259s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.05041 and accuracy 0.000 in 0.6161s\n",
      "Epoch 30 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.04980 and accuracy 0.000 in 0.6291s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.05041 and accuracy 0.000 in 0.6677s\n",
      "Epoch 31 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.04782 and accuracy 0.000 in 0.6423s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.05040 and accuracy 0.000 in 0.6071s\n",
      "Epoch 32 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.04509 and accuracy 0.000 in 0.6462s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.05042 and accuracy 0.000 in 0.6377s\n",
      "Epoch 33 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.04849 and accuracy 0.000 in 0.6631s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.05042 and accuracy 0.000 in 0.6462s\n",
      "Epoch 34 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.04954 and accuracy 0.000 in 0.6317s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.05042 and accuracy 0.000 in 0.6158s\n",
      "Epoch 35 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.04858 and accuracy 0.000 in 0.6465s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.05041 and accuracy 0.000 in 0.6283s\n",
      "Epoch 36 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.04871 and accuracy 0.000 in 0.6378s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.05041 and accuracy 0.000 in 0.6343s\n",
      "Epoch 37 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.04320 and accuracy 0.000 in 0.6458s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.05039 and accuracy 0.000 in 0.6292s\n",
      "Epoch 38 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.04881 and accuracy 0.000 in 0.6552s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.05038 and accuracy 0.000 in 0.6369s\n",
      "Epoch 39 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.04283 and accuracy 0.000 in 0.6866s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.05038 and accuracy 0.000 in 0.6533s\n",
      "Epoch 40 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.05153 and accuracy 0.000 in 0.6245s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.05037 and accuracy 0.000 in 0.6057s\n",
      "Epoch 41 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.05198 and accuracy 0.000 in 0.6345s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.05036 and accuracy 0.000 in 0.6050s\n",
      "Epoch 42 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.04665 and accuracy 0.000 in 0.6931s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.05035 and accuracy 0.000 in 0.6363s\n",
      "Epoch 43 of 100\n",
      "  Training...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7fa903a113c8>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/site-packages/torch/utils/data/dataloader.py\", line 349, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/site-packages/torch/utils/data/dataloader.py\", line 328, in _shutdown_workers\n",
      "    self.worker_result_queue.get()\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/queues.py\", line 337, in get\n",
      "    return _ForkingPickler.loads(res)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/site-packages/torch/multiprocessing/reductions.py\", line 70, in rebuild_storage_fd\n",
      "    fd = df.detach()\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/resource_sharer.py\", line 57, in detach\n",
      "    with _resource_sharer.get_connection(self._id) as conn:\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/resource_sharer.py\", line 87, in get_connection\n",
      "    c = Client(address, authkey=process.current_process().authkey)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 493, in Client\n",
      "    answer_challenge(c, authkey)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 732, in answer_challenge\n",
      "    message = connection.recv_bytes(256)         # reject large message\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 216, in recv_bytes\n",
      "    buf = self._recv_bytes(maxlength)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 407, in _recv_bytes\n",
      "    buf = self._recv(4)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 383, in _recv\n",
      "    raise EOFError\n",
      "EOFError: \n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "   >> Epoch finished with loss 64.04489 and accuracy 0.000 in 0.5181s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.05036 and accuracy 0.000 in 0.6087s\n",
      "Epoch 44 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.04637 and accuracy 0.000 in 0.6467s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.05033 and accuracy 0.000 in 0.6290s\n",
      "Epoch 45 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.04744 and accuracy 0.000 in 0.6461s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.05033 and accuracy 0.000 in 0.6007s\n",
      "Epoch 46 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.04862 and accuracy 0.000 in 0.6594s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.05032 and accuracy 0.000 in 0.6267s\n",
      "Epoch 47 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.04684 and accuracy 0.000 in 0.6529s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.05032 and accuracy 0.000 in 0.6182s\n",
      "Epoch 48 of 100\n",
      "  Training...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7fa903a113c8>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/site-packages/torch/utils/data/dataloader.py\", line 349, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/site-packages/torch/utils/data/dataloader.py\", line 328, in _shutdown_workers\n",
      "    self.worker_result_queue.get()\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/queues.py\", line 337, in get\n",
      "    return _ForkingPickler.loads(res)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/site-packages/torch/multiprocessing/reductions.py\", line 70, in rebuild_storage_fd\n",
      "    fd = df.detach()\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/resource_sharer.py\", line 57, in detach\n",
      "    with _resource_sharer.get_connection(self._id) as conn:\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/resource_sharer.py\", line 87, in get_connection\n",
      "    c = Client(address, authkey=process.current_process().authkey)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 494, in Client\n",
      "    deliver_challenge(c, authkey)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 722, in deliver_challenge\n",
      "    response = connection.recv_bytes(256)        # reject large message\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 216, in recv_bytes\n",
      "    buf = self._recv_bytes(maxlength)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 407, in _recv_bytes\n",
      "    buf = self._recv(4)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 379, in _recv\n",
      "    chunk = read(handle, remaining)\n",
      "ConnectionResetError: [Errno 104] Connection reset by peer\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "   >> Epoch finished with loss 64.04355 and accuracy 0.000 in 0.5279s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.05032 and accuracy 0.000 in 0.6319s\n",
      "Epoch 49 of 100\n",
      "  Training...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7fa903a113c8>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/site-packages/torch/utils/data/dataloader.py\", line 349, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/site-packages/torch/utils/data/dataloader.py\", line 328, in _shutdown_workers\n",
      "    self.worker_result_queue.get()\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/queues.py\", line 337, in get\n",
      "    return _ForkingPickler.loads(res)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/site-packages/torch/multiprocessing/reductions.py\", line 70, in rebuild_storage_fd\n",
      "    fd = df.detach()\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/resource_sharer.py\", line 57, in detach\n",
      "    with _resource_sharer.get_connection(self._id) as conn:\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/resource_sharer.py\", line 87, in get_connection\n",
      "    c = Client(address, authkey=process.current_process().authkey)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 493, in Client\n",
      "    answer_challenge(c, authkey)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 732, in answer_challenge\n",
      "    message = connection.recv_bytes(256)         # reject large message\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 216, in recv_bytes\n",
      "    buf = self._recv_bytes(maxlength)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 407, in _recv_bytes\n",
      "    buf = self._recv(4)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 383, in _recv\n",
      "    raise EOFError\n",
      "EOFError: \n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "   >> Epoch finished with loss 64.04700 and accuracy 0.000 in 0.5361s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.05032 and accuracy 0.000 in 0.6136s\n",
      "Epoch 50 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.04736 and accuracy 0.000 in 0.6463s\n",
      "  Validating...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7fa903a113c8>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/site-packages/torch/utils/data/dataloader.py\", line 349, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/site-packages/torch/utils/data/dataloader.py\", line 328, in _shutdown_workers\n",
      "    self.worker_result_queue.get()\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/queues.py\", line 337, in get\n",
      "    return _ForkingPickler.loads(res)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/site-packages/torch/multiprocessing/reductions.py\", line 70, in rebuild_storage_fd\n",
      "    fd = df.detach()\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/resource_sharer.py\", line 57, in detach\n",
      "    with _resource_sharer.get_connection(self._id) as conn:\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/resource_sharer.py\", line 87, in get_connection\n",
      "    c = Client(address, authkey=process.current_process().authkey)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 493, in Client\n",
      "    answer_challenge(c, authkey)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 732, in answer_challenge\n",
      "    message = connection.recv_bytes(256)         # reject large message\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 216, in recv_bytes\n",
      "    buf = self._recv_bytes(maxlength)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 407, in _recv_bytes\n",
      "    buf = self._recv(4)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 383, in _recv\n",
      "    raise EOFError\n",
      "EOFError: \n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "    ....iteration 1/55470\r",
      "   >> Epoch finished with loss 64.05032 and accuracy 0.000 in 0.5092s\n",
      "Epoch 51 of 100\n",
      "  Training...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7fa903a113c8>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/site-packages/torch/utils/data/dataloader.py\", line 349, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/site-packages/torch/utils/data/dataloader.py\", line 328, in _shutdown_workers\n",
      "    self.worker_result_queue.get()\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/queues.py\", line 337, in get\n",
      "    return _ForkingPickler.loads(res)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/site-packages/torch/multiprocessing/reductions.py\", line 70, in rebuild_storage_fd\n",
      "    fd = df.detach()\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/resource_sharer.py\", line 57, in detach\n",
      "    with _resource_sharer.get_connection(self._id) as conn:\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/resource_sharer.py\", line 87, in get_connection\n",
      "    c = Client(address, authkey=process.current_process().authkey)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 493, in Client\n",
      "    answer_challenge(c, authkey)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 732, in answer_challenge\n",
      "    message = connection.recv_bytes(256)         # reject large message\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 216, in recv_bytes\n",
      "    buf = self._recv_bytes(maxlength)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 407, in _recv_bytes\n",
      "    buf = self._recv(4)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 383, in _recv\n",
      "    raise EOFError\n",
      "EOFError: \n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "   >> Epoch finished with loss 64.04883 and accuracy 0.000 in 0.5262s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.05032 and accuracy 0.000 in 0.6049s\n",
      "Epoch 52 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.04617 and accuracy 0.000 in 0.6211s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.05030 and accuracy 0.000 in 0.6087s\n",
      "Epoch 53 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.04654 and accuracy 0.000 in 0.6544s\n",
      "  Validating...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7fa903a113c8>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/site-packages/torch/utils/data/dataloader.py\", line 349, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/site-packages/torch/utils/data/dataloader.py\", line 328, in _shutdown_workers\n",
      "    self.worker_result_queue.get()\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/queues.py\", line 337, in get\n",
      "    return _ForkingPickler.loads(res)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/site-packages/torch/multiprocessing/reductions.py\", line 70, in rebuild_storage_fd\n",
      "    fd = df.detach()\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/resource_sharer.py\", line 57, in detach\n",
      "    with _resource_sharer.get_connection(self._id) as conn:\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/resource_sharer.py\", line 87, in get_connection\n",
      "    c = Client(address, authkey=process.current_process().authkey)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 493, in Client\n",
      "    answer_challenge(c, authkey)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 732, in answer_challenge\n",
      "    message = connection.recv_bytes(256)         # reject large message\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 216, in recv_bytes\n",
      "    buf = self._recv_bytes(maxlength)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 407, in _recv_bytes\n",
      "    buf = self._recv(4)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 383, in _recv\n",
      "    raise EOFError\n",
      "EOFError: \n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "   >> Epoch finished with loss 64.05031 and accuracy 0.000 in 0.4960s\n",
      "Epoch 54 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.04597 and accuracy 0.000 in 0.6777s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.05030 and accuracy 0.000 in 0.6633s\n",
      "Epoch 55 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.04375 and accuracy 0.000 in 0.6459s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.05029 and accuracy 0.000 in 0.6274s\n",
      "Epoch 56 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.04526 and accuracy 0.000 in 0.6585s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.05029 and accuracy 0.000 in 0.6292s\n",
      "Epoch 57 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.04860 and accuracy 0.000 in 0.6309s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.05029 and accuracy 0.000 in 0.6148s\n",
      "Epoch 58 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.04485 and accuracy 0.000 in 0.7024s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.05029 and accuracy 0.000 in 0.6632s\n",
      "Epoch 59 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.04454 and accuracy 0.000 in 0.6590s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.05027 and accuracy 0.000 in 0.6418s\n",
      "Epoch 60 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.04677 and accuracy 0.000 in 0.6281s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.05026 and accuracy 0.000 in 0.6471s\n",
      "Epoch 61 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.04307 and accuracy 0.000 in 0.6424s\n",
      "  Validating...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7fa903a113c8>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/site-packages/torch/utils/data/dataloader.py\", line 349, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/site-packages/torch/utils/data/dataloader.py\", line 328, in _shutdown_workers\n",
      "    self.worker_result_queue.get()\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/queues.py\", line 337, in get\n",
      "    return _ForkingPickler.loads(res)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/site-packages/torch/multiprocessing/reductions.py\", line 70, in rebuild_storage_fd\n",
      "    fd = df.detach()\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/resource_sharer.py\", line 58, in detach\n",
      "    return reduction.recv_handle(conn)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/reduction.py\", line 182, in recv_handle\n",
      "    return recvfds(s, 1)[0]\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/reduction.py\", line 153, in recvfds\n",
      "    msg, ancdata, flags, addr = sock.recvmsg(1, socket.CMSG_LEN(bytes_size))\n",
      "ConnectionResetError: [Errno 104] Connection reset by peer\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "   >> Epoch finished with loss 64.05025 and accuracy 0.000 in 0.5111s\n",
      "Epoch 62 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.04222 and accuracy 0.000 in 0.6179s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.05025 and accuracy 0.000 in 0.6298s\n",
      "Epoch 63 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.04831 and accuracy 0.000 in 0.7042s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.05023 and accuracy 0.000 in 0.6232s\n",
      "Epoch 64 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.04570 and accuracy 0.000 in 0.6303s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.05023 and accuracy 0.000 in 0.6256s\n",
      "Epoch 65 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.04430 and accuracy 0.000 in 0.6484s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.05022 and accuracy 0.000 in 0.6077s\n",
      "Epoch 66 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.04522 and accuracy 0.000 in 0.6514s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.05021 and accuracy 0.000 in 0.6162s\n",
      "Epoch 67 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.04623 and accuracy 0.000 in 0.6334s\n",
      "  Validating...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7fa903a113c8>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/site-packages/torch/utils/data/dataloader.py\", line 349, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/site-packages/torch/utils/data/dataloader.py\", line 328, in _shutdown_workers\n",
      "    self.worker_result_queue.get()\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/queues.py\", line 337, in get\n",
      "    return _ForkingPickler.loads(res)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/site-packages/torch/multiprocessing/reductions.py\", line 70, in rebuild_storage_fd\n",
      "    fd = df.detach()\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/resource_sharer.py\", line 57, in detach\n",
      "    with _resource_sharer.get_connection(self._id) as conn:\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/resource_sharer.py\", line 87, in get_connection\n",
      "    c = Client(address, authkey=process.current_process().authkey)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 493, in Client\n",
      "    answer_challenge(c, authkey)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 737, in answer_challenge\n",
      "    response = connection.recv_bytes(256)        # reject large message\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 216, in recv_bytes\n",
      "    buf = self._recv_bytes(maxlength)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 407, in _recv_bytes\n",
      "    buf = self._recv(4)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 379, in _recv\n",
      "    chunk = read(handle, remaining)\n",
      "ConnectionResetError: [Errno 104] Connection reset by peer\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "   >> Epoch finished with loss 64.05021 and accuracy 0.000 in 0.4950s\n",
      "Epoch 68 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.04165 and accuracy 0.000 in 0.6597s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.05020 and accuracy 0.000 in 0.6321s\n",
      "Epoch 69 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.04214 and accuracy 0.000 in 0.6376s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.05019 and accuracy 0.000 in 0.6070s\n",
      "Epoch 70 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.04234 and accuracy 0.000 in 0.6506s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.05018 and accuracy 0.000 in 0.6120s\n",
      "Epoch 71 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.05029 and accuracy 0.000 in 0.6329s\n",
      "  Validating...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7fa903a113c8>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/site-packages/torch/utils/data/dataloader.py\", line 349, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/site-packages/torch/utils/data/dataloader.py\", line 328, in _shutdown_workers\n",
      "    self.worker_result_queue.get()\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/queues.py\", line 337, in get\n",
      "    return _ForkingPickler.loads(res)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/site-packages/torch/multiprocessing/reductions.py\", line 70, in rebuild_storage_fd\n",
      "    fd = df.detach()\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/resource_sharer.py\", line 57, in detach\n",
      "    with _resource_sharer.get_connection(self._id) as conn:\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/resource_sharer.py\", line 87, in get_connection\n",
      "    c = Client(address, authkey=process.current_process().authkey)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 493, in Client\n",
      "    answer_challenge(c, authkey)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 732, in answer_challenge\n",
      "    message = connection.recv_bytes(256)         # reject large message\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 216, in recv_bytes\n",
      "    buf = self._recv_bytes(maxlength)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 407, in _recv_bytes\n",
      "    buf = self._recv(4)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 383, in _recv\n",
      "    raise EOFError\n",
      "EOFError: \n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "   >> Epoch finished with loss 64.05019 and accuracy 0.000 in 0.4956s\n",
      "Epoch 72 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.04490 and accuracy 0.000 in 0.6410s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.05017 and accuracy 0.000 in 0.6234s\n",
      "Epoch 73 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.04665 and accuracy 0.000 in 0.6506s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.05016 and accuracy 0.000 in 0.6470s\n",
      "Epoch 74 of 100\n",
      "  Training...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7fa903a113c8>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/site-packages/torch/utils/data/dataloader.py\", line 349, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/site-packages/torch/utils/data/dataloader.py\", line 328, in _shutdown_workers\n",
      "    self.worker_result_queue.get()\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/queues.py\", line 337, in get\n",
      "    return _ForkingPickler.loads(res)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/site-packages/torch/multiprocessing/reductions.py\", line 70, in rebuild_storage_fd\n",
      "    fd = df.detach()\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/resource_sharer.py\", line 57, in detach\n",
      "    with _resource_sharer.get_connection(self._id) as conn:\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/resource_sharer.py\", line 87, in get_connection\n",
      "    c = Client(address, authkey=process.current_process().authkey)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 493, in Client\n",
      "    answer_challenge(c, authkey)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 732, in answer_challenge\n",
      "    message = connection.recv_bytes(256)         # reject large message\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 216, in recv_bytes\n",
      "    buf = self._recv_bytes(maxlength)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 407, in _recv_bytes\n",
      "    buf = self._recv(4)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 383, in _recv\n",
      "    raise EOFError\n",
      "EOFError: \n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "    ....iteration 1/55470\r",
      "   >> Epoch finished with loss 64.04468 and accuracy 0.000 in 0.5098s\n",
      "  Validating...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7fa903a113c8>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/site-packages/torch/utils/data/dataloader.py\", line 349, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/site-packages/torch/utils/data/dataloader.py\", line 328, in _shutdown_workers\n",
      "    self.worker_result_queue.get()\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/queues.py\", line 337, in get\n",
      "    return _ForkingPickler.loads(res)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/site-packages/torch/multiprocessing/reductions.py\", line 70, in rebuild_storage_fd\n",
      "    fd = df.detach()\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/resource_sharer.py\", line 57, in detach\n",
      "    with _resource_sharer.get_connection(self._id) as conn:\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/resource_sharer.py\", line 87, in get_connection\n",
      "    c = Client(address, authkey=process.current_process().authkey)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 493, in Client\n",
      "    answer_challenge(c, authkey)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 732, in answer_challenge\n",
      "    message = connection.recv_bytes(256)         # reject large message\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 216, in recv_bytes\n",
      "    buf = self._recv_bytes(maxlength)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 407, in _recv_bytes\n",
      "    buf = self._recv(4)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 383, in _recv\n",
      "    raise EOFError\n",
      "EOFError: \n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "   >> Epoch finished with loss 64.05016 and accuracy 0.000 in 0.4937s\n",
      "Epoch 75 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.04610 and accuracy 0.000 in 0.6176s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.05013 and accuracy 0.000 in 0.6343s\n",
      "Epoch 76 of 100\n",
      "  Training...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7fa903a113c8>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/site-packages/torch/utils/data/dataloader.py\", line 349, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/site-packages/torch/utils/data/dataloader.py\", line 328, in _shutdown_workers\n",
      "    self.worker_result_queue.get()\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/queues.py\", line 337, in get\n",
      "    return _ForkingPickler.loads(res)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/site-packages/torch/multiprocessing/reductions.py\", line 70, in rebuild_storage_fd\n",
      "    fd = df.detach()\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/resource_sharer.py\", line 57, in detach\n",
      "    with _resource_sharer.get_connection(self._id) as conn:\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/resource_sharer.py\", line 87, in get_connection\n",
      "    c = Client(address, authkey=process.current_process().authkey)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 493, in Client\n",
      "    answer_challenge(c, authkey)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 732, in answer_challenge\n",
      "    message = connection.recv_bytes(256)         # reject large message\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 216, in recv_bytes\n",
      "    buf = self._recv_bytes(maxlength)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 407, in _recv_bytes\n",
      "    buf = self._recv(4)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 383, in _recv\n",
      "    raise EOFError\n",
      "EOFError: \n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "   >> Epoch finished with loss 64.04243 and accuracy 0.000 in 0.5178s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.05013 and accuracy 0.000 in 0.6198s\n",
      "Epoch 77 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.04047 and accuracy 0.000 in 0.6238s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.05012 and accuracy 0.000 in 0.6148s\n",
      "Epoch 78 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.04522 and accuracy 0.000 in 0.6665s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.05010 and accuracy 0.000 in 0.6120s\n",
      "Epoch 79 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.04326 and accuracy 0.000 in 0.6289s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.05009 and accuracy 0.000 in 0.6373s\n",
      "Epoch 80 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.04831 and accuracy 0.000 in 0.6722s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.05009 and accuracy 0.000 in 0.6121s\n",
      "Epoch 81 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.04279 and accuracy 0.000 in 0.6512s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.05009 and accuracy 0.000 in 0.5966s\n",
      "Epoch 82 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.04510 and accuracy 0.000 in 0.6548s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.05009 and accuracy 0.000 in 0.6039s\n",
      "Epoch 83 of 100\n",
      "  Training...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7fa903a113c8>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/site-packages/torch/utils/data/dataloader.py\", line 349, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/site-packages/torch/utils/data/dataloader.py\", line 328, in _shutdown_workers\n",
      "    self.worker_result_queue.get()\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/queues.py\", line 337, in get\n",
      "    return _ForkingPickler.loads(res)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/site-packages/torch/multiprocessing/reductions.py\", line 70, in rebuild_storage_fd\n",
      "    fd = df.detach()\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/resource_sharer.py\", line 57, in detach\n",
      "    with _resource_sharer.get_connection(self._id) as conn:\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/resource_sharer.py\", line 87, in get_connection\n",
      "    c = Client(address, authkey=process.current_process().authkey)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 493, in Client\n",
      "    answer_challenge(c, authkey)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 732, in answer_challenge\n",
      "    message = connection.recv_bytes(256)         # reject large message\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 216, in recv_bytes\n",
      "    buf = self._recv_bytes(maxlength)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 407, in _recv_bytes\n",
      "    buf = self._recv(4)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 383, in _recv\n",
      "    raise EOFError\n",
      "EOFError: \n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "   >> Epoch finished with loss 64.04398 and accuracy 0.000 in 0.5281s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.05006 and accuracy 0.000 in 0.6085s\n",
      "Epoch 84 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.04341 and accuracy 0.000 in 0.6348s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.05005 and accuracy 0.000 in 0.6141s\n",
      "Epoch 85 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.04154 and accuracy 0.000 in 0.6222s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.05006 and accuracy 0.000 in 0.6163s\n",
      "Epoch 86 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.04565 and accuracy 0.000 in 0.6318s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.05004 and accuracy 0.000 in 0.6067s\n",
      "Epoch 87 of 100\n",
      "  Training...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7fa903a113c8>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/site-packages/torch/utils/data/dataloader.py\", line 349, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/site-packages/torch/utils/data/dataloader.py\", line 328, in _shutdown_workers\n",
      "    self.worker_result_queue.get()\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/queues.py\", line 337, in get\n",
      "    return _ForkingPickler.loads(res)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/site-packages/torch/multiprocessing/reductions.py\", line 70, in rebuild_storage_fd\n",
      "    fd = df.detach()\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/resource_sharer.py\", line 57, in detach\n",
      "    with _resource_sharer.get_connection(self._id) as conn:\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/resource_sharer.py\", line 87, in get_connection\n",
      "    c = Client(address, authkey=process.current_process().authkey)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 493, in Client\n",
      "    answer_challenge(c, authkey)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 732, in answer_challenge\n",
      "    message = connection.recv_bytes(256)         # reject large message\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 216, in recv_bytes\n",
      "    buf = self._recv_bytes(maxlength)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 407, in _recv_bytes\n",
      "    buf = self._recv(4)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 383, in _recv\n",
      "    raise EOFError\n",
      "EOFError: \n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "   >> Epoch finished with loss 64.04372 and accuracy 0.000 in 0.5242s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.05003 and accuracy 0.000 in 0.6481s\n",
      "Epoch 88 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.04344 and accuracy 0.000 in 0.6879s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.05002 and accuracy 0.000 in 0.6281s\n",
      "Epoch 89 of 100\n",
      "  Training...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7fa903a113c8>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/site-packages/torch/utils/data/dataloader.py\", line 349, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/site-packages/torch/utils/data/dataloader.py\", line 328, in _shutdown_workers\n",
      "    self.worker_result_queue.get()\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/queues.py\", line 337, in get\n",
      "    return _ForkingPickler.loads(res)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/site-packages/torch/multiprocessing/reductions.py\", line 70, in rebuild_storage_fd\n",
      "    fd = df.detach()\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/resource_sharer.py\", line 57, in detach\n",
      "    with _resource_sharer.get_connection(self._id) as conn:\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/resource_sharer.py\", line 87, in get_connection\n",
      "    c = Client(address, authkey=process.current_process().authkey)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 493, in Client\n",
      "    answer_challenge(c, authkey)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 732, in answer_challenge\n",
      "    message = connection.recv_bytes(256)         # reject large message\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 216, in recv_bytes\n",
      "    buf = self._recv_bytes(maxlength)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 407, in _recv_bytes\n",
      "    buf = self._recv(4)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 383, in _recv\n",
      "    raise EOFError\n",
      "EOFError: \n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "   >> Epoch finished with loss 64.04165 and accuracy 0.000 in 0.5178s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.05000 and accuracy 0.000 in 0.6125s\n",
      "Epoch 90 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.04350 and accuracy 0.000 in 0.6446s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.04998 and accuracy 0.000 in 0.6100s\n",
      "Epoch 91 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.04327 and accuracy 0.000 in 0.6698s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.04999 and accuracy 0.000 in 0.6270s\n",
      "Epoch 92 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.03993 and accuracy 0.000 in 0.6375s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.04996 and accuracy 0.000 in 0.6757s\n",
      "Epoch 93 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.04167 and accuracy 0.000 in 0.6540s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.04996 and accuracy 0.000 in 0.6299s\n",
      "Epoch 94 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.04437 and accuracy 0.000 in 0.6601s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.04995 and accuracy 0.000 in 0.6242s\n",
      "Epoch 95 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.04076 and accuracy 0.000 in 0.6818s\n",
      "  Validating...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7fa903a113c8>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/site-packages/torch/utils/data/dataloader.py\", line 349, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/site-packages/torch/utils/data/dataloader.py\", line 328, in _shutdown_workers\n",
      "    self.worker_result_queue.get()\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/queues.py\", line 337, in get\n",
      "    return _ForkingPickler.loads(res)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/site-packages/torch/multiprocessing/reductions.py\", line 70, in rebuild_storage_fd\n",
      "    fd = df.detach()\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/resource_sharer.py\", line 57, in detach\n",
      "    with _resource_sharer.get_connection(self._id) as conn:\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/resource_sharer.py\", line 87, in get_connection\n",
      "    c = Client(address, authkey=process.current_process().authkey)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 493, in Client\n",
      "    answer_challenge(c, authkey)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 732, in answer_challenge\n",
      "    message = connection.recv_bytes(256)         # reject large message\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 216, in recv_bytes\n",
      "    buf = self._recv_bytes(maxlength)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 407, in _recv_bytes\n",
      "    buf = self._recv(4)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 383, in _recv\n",
      "    raise EOFError\n",
      "EOFError: \n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "   >> Epoch finished with loss 64.04996 and accuracy 0.000 in 0.4654s\n",
      "Epoch 96 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.04284 and accuracy 0.000 in 0.6536s\n",
      "  Validating...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7fa903a113c8>>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/site-packages/torch/utils/data/dataloader.py\", line 349, in __del__\n",
      "    self._shutdown_workers()\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/site-packages/torch/utils/data/dataloader.py\", line 328, in _shutdown_workers\n",
      "    self.worker_result_queue.get()\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/queues.py\", line 337, in get\n",
      "    return _ForkingPickler.loads(res)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/site-packages/torch/multiprocessing/reductions.py\", line 70, in rebuild_storage_fd\n",
      "    fd = df.detach()\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/resource_sharer.py\", line 57, in detach\n",
      "    with _resource_sharer.get_connection(self._id) as conn:\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/resource_sharer.py\", line 87, in get_connection\n",
      "    c = Client(address, authkey=process.current_process().authkey)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 493, in Client\n",
      "    answer_challenge(c, authkey)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 737, in answer_challenge\n",
      "    response = connection.recv_bytes(256)        # reject large message\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 216, in recv_bytes\n",
      "    buf = self._recv_bytes(maxlength)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 407, in _recv_bytes\n",
      "    buf = self._recv(4)\n",
      "  File \"/home/ubuntu/anaconda3/envs/AI_Proj/lib/python3.6/multiprocessing/connection.py\", line 379, in _recv\n",
      "    chunk = read(handle, remaining)\n",
      "ConnectionResetError: [Errno 104] Connection reset by peer\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "   >> Epoch finished with loss 64.04993 and accuracy 0.000 in 0.5914s\n",
      "Epoch 97 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.04399 and accuracy 0.000 in 0.6580s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.04992 and accuracy 0.000 in 0.6242s\n",
      "Epoch 98 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.04639 and accuracy 0.000 in 0.6290s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.04991 and accuracy 0.000 in 0.6169s\n",
      "Epoch 99 of 100\n",
      "  Training...\n",
      "   >> Epoch finished with loss 64.04174 and accuracy 0.000 in 0.6830s\n",
      "  Validating...\n",
      "   >> Epoch finished with loss 64.04990 and accuracy 0.000 in 0.6187s\n"
     ]
    }
   ],
   "source": [
    "trained_model, statistics = trainer.train(train_dataset, val_dataset, save_every=50, collate_fn=collate, e_break=1, epoch=100)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2018-07-11T15:00:17.895877Z",
     "start_time": "2018-07-11T15:00:17.683710Z"
    }
   },
   "outputs": [
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAYoAAAEICAYAAABBBrPDAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAADl0RVh0U29mdHdhcmUAbWF0cGxvdGxpYiB2ZXJzaW9uIDIuMi4yLCBodHRwOi8vbWF0cGxvdGxpYi5vcmcvhp/UCwAAIABJREFUeJzsvXucXWWV5/1d51r3pHIjJBVIYpGQBBEwBHCU1qBAox3tbt4QX3WijeMotDowtvQM3UiD3aDY0PQL7eAIDm0rUdJqMtok0gheWiCECELCJZEEkooklcqlKnU5dS7r/WPvZ5+9z9nnUpWq1Kmq5/v51Ic6+36S8Kz9W7/1rEdUFYvFYrFYShEZ6wewWCwWS21jA4XFYrFYymIDhcVisVjKYgOFxWKxWMpiA4XFYrFYymIDhcVisVjKYgOFxWKxWMpiA8U4QUT2iMh7x/o5LBbL5MMGCovFYrGUxQaKcY6I/BcR2SUih0Vko4jMcbeLiNwlIgdF5JiI/FZEznL3XSEiO0SkR0Q6ROQLvut9QESeE5GjIvJrETnbt+8G9/geEXlFRC45+d/YYrGcbGygGMeIyErgNmA1cCrwOrDO3X0pcDGwCJgKXAV0ufvuB/6rqjYDZwE/c693HvAA8F+B6cB9wEYRSYrIYuDPgfPd8y4D9ozyV7RYLDWADRTjm48AD6jqNlVNAf8DuEhE5gNpoBk4ExBVfUlVf++elwaWikiLqh5R1W3u9v8C3KeqT6tqVlUfBFLAhUAWSLrnxVV1j6r+7mR9UYvFMnbYQDG+mYOjIgBQ1eM4qmGuqv4MuAe4FzggIt8QkRb30D8FrgBeF5Gfi8hF7vbTgf/upp2OishRYB4wR1V3Af8NuBk4KCLrTJrLYrFMbGygGN/sxxncARCRRpyUUQeAqv6jqr4dWIaTgvoLd/szqvpBYBbwI+D77iX2An+rqlN9Pw2q+pB73ndV9Z3uPRX4ysn4khaLZWyxgWJ8EReROvODM8B/QkTOEZEk8HfA06q6R0TOF5ELRCQO9AIDQFZEEiLyERGZoqppoBsnrQTwv4FPu+eJiDSKyPtFpFlEFovISvc+A0C/7zyLxTKBsYFifPFvOAO0+XkX8NfAvwK/B94CrHGPbcEZ+I/gpKe6gK+5+z4G7BGRbuDTwEcBVHUrjk9xj3veLuDj7jlJ4HbgEPAmjhr5n6PyLS0WS00hduEii8VisZTDKgqLxWKxlMUGCovFYrGUpapAISJTRWS9iLwsIi/5yikRkS+IiIrIjBLnrhWRne7PWt/2J9zZvc+5P7MKzrvSve7y4X45i8VisZw4sSqPuxvYpKpXikgCaAAQkXnA+4A3wk4SkWnAl4DlOOWUz4rIRlU94h7yEddALTyvGfgc8PRQvozFYrFYRp6KgcKdpHUxbvWLqg4Cg+7uu4AvAhtKnH4Z8KiqHnav9ShwOfBQhdveCnwV+EKF4wCYMWOGzp8/v5pDLZYh8+yzzx5S1ZljcW/7b9symlT7b7saRbEQ6AS+JSJvA54FPg9cAnSo6vMiUurcuTiTuAz73G2Gb4lIFqe888uqqiJyLjBPVX/sb1ZXiIh8CvgUwGmnncbWrUXCxGIZEUTk9cpHjQ7z58+3/7Yto0a1/7ar8ShiwHnA11X1XJzJWzcDNwI3VXqOkG2mHvcjqvpWnLkA7wI+JiIRHJXy3ys9lKp+Q1WXq+rymTPH5GXPYrFYJgXVBIp9wD5VNX7BepzAsQB4XkT2AG3ANhGZHXLuPN/nNpy2E6iqaTPRA3wXWIHTxO4s4An3uhfidC+1hrbFYrGMERUDhaq+Cex120yDk3LapqqzVHW+qs7HCQjnucf62QxcKiKtItKK0/p6s4jETJWU22LiA8CLqnpMVWf4rvsUsCrM8LZYLBbLyaHaqqfPAt9xK55eAz5R6kD37f/TqvpJVT0sIrcCz7i7b3G3NeIEjDgQBf4dp92ExWKxWGqMqgKFqj6HU+Jaav983+9bgU/6Pj+AsxiO//he4O1V3Pfd1TyfxWKxWEYPOzPbYrFYLGWxgcJisVgsZZl0gUJVee7B50j3p8f6USwWi8Vj61bnpxap1syeMBx6+RAbPr6BZHOSJX+yZKwfx2KxWAD44hdBBB57bKyfpJhJFygy/Rnnv6nMGD+JxWKx5BkcrHzMWDHpAkU27azemcvkxvhJLBaLJU8u5/zUIpPOo8ilnb8JGygsFkstoQqZGk10TLpAYRSFZu0SsBONTZs2sXjxYtrb27n99tuL9qdSKa666ira29u54IIL2LNnj7fvtttuo729ncWLF7N58+bANYGzRGSXiPyl2S4iC0TkaXedle+5k1ERketFZIeI/FZEHhOR033nnCYiP3XXdNkhIvNH/k/BMl7J5WygqBmsopiYZLNZrr32Wh555BF27NjBQw89xI4dOwLH3H///bS2trJr1y6uu+46brjhBgB27NjBunXr2L59O5s2beKaa64hm8161wReBZYCHxaRpe7lvgLcpapnAEeAq93tvwGWq+rZOH3Rvup7hH8G7lDVJTi9zQ6Oxp+FZXxiA0UN4XkUWRsoJhJbtmyhvb2dhQsXkkgkWLNmDRs2BJdJ2bBhA2vXOossXnnllTz22GOoKhs2bGDNmjUkk0kWLFhAe3s7W7Zs8a4JDLrrsKwDPihOX/2VOIEA4EHgQwCq+riq9rnbn8JphIkbYGKq+qh73HHfcRYLuRxks2P9FOFMukBhFcXEpKOjg3nz8o2K29ra6OjoKHlMLBZjypQpdHV1lTy3cDv59VSmA0dVNVOwvZCrgUfc3xcBR0XkByLyGxG5Q0SiYd9FRD4lIltFZGtnZ2fVfwaW8Y1VFDWErXqamKgWe06FC2qVOmYo23HWUym3zoo5/6M4/dHucDfFcNZd+QJwPs6CYB8PvYFda2VSYgNFDWEUhTWzJxZtbW3s3ZtfTHHfvn3MmTOn5DGZTIZjx44xbdq0kucWbie/nsohYKqIxAq2AyAi78VZ2GuVqqbMZYHfqOprrhL5Ec66LhYLYKueagqjJKyimFicf/757Ny5k927dzM4OMi6detYtWpV4JhVq1bx4IMPArB+/XpWrlyJiLBq1SrWrVtHKpVi9+7d7Ny5kxUrVnjXBBJuVdMaYKM6UuNx4Er30mtx1413l/K9DydI+M3qZ4BWETESYSUQdNstkxqrKGoIm3qamMRiMe655x4uu+wylixZwurVq1m2bBk33XQTGzduBODqq6+mq6uL9vZ27rzzTq+EdtmyZaxevZqlS5dy+eWXc++99xKNRr1r4vgLLwHfV9Xt7i1vAK4XkV04nsX97vY7gCbgYRF5TkQ2AqhqFift9JiIvICTvrJrsFg8ajlQSIk87Lhi+fLlWu0C9Fv/11Z+8pmfcPFNF/Oev3nPKD+ZZSIgIs+q6pgsxzuUf9uW8c2ZZ8KBA3DkyMm7Z7X/tq2isFgslhqglhXFpAsU1sy2WCy1iDWzawirKCwWSy1iFUUNYSfcWSyWWsQEilq0jasKFCIyVUTWi8jLbkOzi3z7viAiKiIzSpy71m2ctlNE1vq2PyEir7iVIc+JyCx3e8mmaiOBbeFhsVhqEdNivBZbjVe7HsXdwCZVvdKtJ28AEJF5wPuAN8JOEpFpwJdwZqgq8KyIbFRV4+t/RFULSzpMU7U+EfkMTlO1q4bypcphFYXFYqlFTIDIZCAa2txl7KioKESkBbgYt05cVQdV9ai7+y7gixS0L/BxGfCoqh52g8OjwOXl7leqqdpIMdE8Cs0pA0cHxvoxLBbLCWJSTrXoU1STeloIdALfcpuZfVNEGkVkFdChqs+XOXcu4O+BUNg87Vtu2umvpbAxj4O/qVqA4TZOm2hVT1vv28rdC+4mO1ijbSctFktV+BVFrVFNoIjh9KT5uqqeC/QCN+P0srmpwrnlmqd9RFXfitMo7V3AxwInFjdVC15kmI3TJpqi2P3vuxk4OkBmoAb/dVkslqoZ74FiH7BPVZ92P6/HCRwLgOdFZA9OemibiMwOOdffp9lrnqaqHe5/e4Dv4izkApRsqjYijLRH8ZsHfsOPPv6jEbnWcOjY4rTSNgHQYrGMT8Z1oFDVN4G9IrLY3XQJsE1VZ6nqfFWdjxMQznOP9bMZuFREWkWkFbgU2CwiMVMlJSJx4APAi+7nUk3VRgQTIEYq9fTGL99g1yO7RuRaQ6Vnfw/d+7qBiaOQLJbJSi0Himqrnj4LfMeteHoN+ESpA0VkOfBpVf2kqh4WkVtxOmcC3OJua8QJGHEgCvw7+QZp/qZqAG+oarAN6Akw0ooiO5gdM3+g45n8wjzme1kslvFJLZvZVQUKVX0Oxy8otX++7/etwCd9nx8AHig4vhd4e4lrvbeaZxouJzqP4ul/fJq6qXW87T+/DYBMKkMmNTZ/sybtBFZRWCzjnVpWFHZm9hB57lvP8cJ3XvA+j6Wi2L/FWyvHehQWyzjHBooa4kSrnrLpLOn+dP7zYBbN6pjM9D7y2hEiMeev0CoKi2V8YwNFDXGi8yhymRyZ/vzfpFETY6EqcpkcsTone2g9CotlfGMDRQ3QsaWDvkN9Q1YUW+7dQudL+Ql9uXQuqChSYxcoNKdEk85cf6soLJbxTS2b2ZMmUHz7fd/mqbufGpJHkRnI8MifPxLwJGpKUWTzisJ6FBbL+KaWFUW15bHjGlUl1Z1i4OjAkKqejh84DgQH4VwmF/jsBYrUGCiKrBKvjzvPZVNPFsu4xgaKMcYM5pmBzJAURe+B3qJjs+lsYFA2pbFjpShs6slimRjUcqCYFKkn0wcpO5D11EA1ZvbxNx1F4R+Ec5lcUdWT/78nE80qsaRNPVksEwEbKMYYkxZK96eHpChM6smvIHLpHNlU1ktdeWplDCbdaU7zVU9WUVgs4xprZo8xRlFkBjLegDrc1JP53VMpNWJmW4/CYhm/+Jc/tYFijDBv+5n+zNDM7JDUkznfVD6NaXls1pbHWiwTAf/ypzZQjBEBRTEcM9tM0lP1vA3jU4xl1VMum7MehcUyAbCBogYwg3hmIDOkCXeFisJ/jqcoxtjMtorCYhn/2EBRAxhF4TezC6uesuksqZ7gGkmemR0SKNL9aXKZHJpzrjNWM7OtR2GxjH9soKgBPI+ijKL41W2/4psXfDOwzaSevHPSQUXhDw4nu+rJBCirKCyW8Y81s2sAz6PoL+1RdHd009PR431O96dJdacCxxYqCn+gONmKwpjxtoWHxTL+qXVFMTlmZod5FAVVT7l0LhAIjJqA0h7FkAJF1t0vAvv2wbRp0NgIqZTzr6Suztm/dy8MDDi/RyLQ2goNDRCPOz8uJnVmzGyberJYxi82UNQAfo/CDLCFiiKXDvZwMka22QfOW7uQYxYHaNz4HWI/7OT9bAFg7v95AXYtdgb13l545RV48004fhwGB+G11yCddgb7wUHnwnV1waAQi+X3FSICCxbA3LkwYwYydRrv4VVmP3+Qbg5Sv3se/FsXJJNw8cWBoGKxWGobGyhqAK8fk6+ENczMzqVzqCoi4hnZDU2wcN/P4UM/oOnXT/FXHCSCwn2gdfWc6Wbvks/uhP/4kaMcolF4y1ugrQ1mznQCwB/9UT4wLFwIXV1w9KijGKJRJ7gMDMAZZ0BTk/tQWTh82Nl+/Di8+qoTfF55hcjBTt7JISL//ksWAfzDevgH98s0NDg/jY3O/WfMgETCucexY8496+udn7e8xQlOuVz+2Pp6J9BMm+acN3Wq81z19cP/OxjIMHB0gKbZTcO+hsUyUbGBYixRBRFPUXhIuKIAJ4CI5Ig+9lP+lIdZ1LuLxKspGJxP+p3v4akf7qeL6Zzxdx9n9qoL+Kez/hcA77v5fbzj+gudwT0ScQb/USR1dICvtN7G5V+6kG1/s5GLPzyXZde82wlAjz/uDP7Hj0NnJxw65Pzrq6uD6dOdANXZCT098PDDTlCIRqGvr/xNW1pg/nznJxaD00+H2bOdc6dPd7affrrzeepUaG52lBDw5F1P8sw9z3B9x/Wj+udisYxHat3MntiB4tOfhr4+GqdcRIQsOZzBO14fd4JHJuOkiJ58kvm7nqaBN9HPfAb+7cecsX8/vTSwe9YFvNq6gj/a8VV6XuniiR/eC8DcxlPIpvN/u9lBN0BETk59gOOxRNDWVg4ym85F74R3vtPZ+cEPVn8hE9hEnEBx6JDjm6RSjprJZJygsnMnHDgAv/sd7NnjbH/kEejvL33tlhZYvBhmzWLJC/tp+/1R+PSrMGeOo3YaGuDSSx1VY7FMYiaEohCRqcA3gbMABf5MVZ90930BuAOYqaqHQs5dC/yV+/HLqvqgu/0J4FTAjDSXqupBEUkC/wy8HegCrlLVPcP6di0tsG4dS7v/hTOIcYRWskRpGEghuQza+LeI6wmscE/Rhxrh0kt5MfJWfvivOd6yfAk9+3tAJOBhFFY9nfTyWDd1FolFkKgMvzzWr3waGuC006o/N5dzAkUm4yiZ3/3OMepzOThyxAkoO3fC/v1EB/uJaRp9+GHk8OHgdZqbnZTXrFnQ3u54Ma2t+aCbSDj7li93FIurUiyWicKECBTA3cAmVb1SRBJAA4CIzAPeB7wRdpKITAO+BCzHCTDPishGVT3iHvIRVd1acNrVwBFVbReRNcBXgKuG8qU87rgDbr6ZF//saxz//iZaOEaMDIeTbQz2Zznns5fAW8+Cd7yDf/2zn/DGr17nv+6+lYaZTey7bhOx5t8QTURDS2qHXPU0wpiqLYkIkVhkbMpjIxFHGQBMmeJ4LyV48s//jWfufYa/PvjXSDbj+C6dnfCTnzhGf2eno1h+8Qt46KHg/zl+Zs50gll3t/P7kiWOapkzBxYtgnPPddJiFss4YtwHChFpAS4GPg6gqoOAKc25C/gisKHE6ZcBj6rqYfdajwKXAw+VueUHgZvd39cD94iIqGrlBSTCaGzkzYX/if/wbWqd08qR3x3hrV++0ZuH0BOdSjfHvL+wVHeKZEuSSCySL4/1laCO9TwKM+EuEo0QjUdrfsKdCWy5dI5IXcJRCS0t8LnPhRycc/wT81c+MAD798OTT8Jzzzmqpb3dMfY3bnSCjKG+3gkYqo73cuGFecXS1uZcd+FCuOCCfJCzWMaYcR8ogIVAJ/AtEXkb8CzweeASoENVn5fSqYC5wF7f533uNsO3RCQL/CtOWkr956hqRkSOAdOBQFpLRD4FfArgtArpksKGfd7yob65FJ5qcP872D1IsiUZGIQDE+760oF008luCmhSTxJ1FEWtz6MoVZYcSiTiKBQ/s2fDeeeFH3/0qBM0fvtbeOopx3eKxZyg8OCDjt+STgfPEXGUyezZThCZORO+9jXHlLdYTjITwcyOAecBn1XVp0Xkbpw3/ouBSyucGxZBzB/JR1S1Q0SacQLFx3C8iXLn5DeofgP4BsDy5cvLqo3CqqdYffFiPyZ1Y/7rVxSF+6B2Uk+RaIRIPDJuFMWopMimTnV+zjwTVq8OP+bwYejocNTFjh3w7LNOufGBA45aef75Ua9Us1hKUeuKopoSnX3APlV92v28HidwLACeF5E9QBuwTURmh5w7z/e5DdgPoKod7n97gO+S95O9c0QkBkwBCtzPoVFoNJt0k38uRaGiMIFCYjIyM7PL8L0//h6P/c/HhnROoaKo9RYeQ1IUw2TTpk0sXryY9vZ2br/99uDOadNILVrEVTfcQPvnPscFP/4xe269FX76U9i2jduuuYb25ctZvHgxmzdvDlwTOEtEdonIX5rtIrJARJ4WkZ0i8j3Xu0NErheRHSLyWxF5TERO9z+GiLSISIeI3DNqfxCWcce4DxSq+iawV0QWu5suAbap6ixVna+q83EG9/PcY/1sBi4VkVYRacVRIJtFJCYiMwBEJA58AHjRPWcjsNb9/UrgZ8P2J1yyAyVSTyEr1xUqipKpp/60l26SiJxQ6unACwc48NsDQzrHb2ZH49Hxk3oapefMZrNce+21PPLII+zYsYOHHnqIHTt2BI65//77aW1tZdeuXVx33XXccMMNAOzYsYN169axfft2Nm3axDXXXEM2m/WuCbwKLAU+LCJL3ct9BbhLVc8AjuAUYQD8BliuqmfjvFR9teBRbwV+PvJ/ApbxzLgPFC6fBb4jIr8FzgH+rtSBIrJcRL4J4JrYtwLPuD+3uNuSOAHjt8BzQAfwv91L3A9MF5FdwPXAX3KCFCmKMqknT1H0+MzsArWBBBVFoilxQooiM5Bh8HiJ1h0l8JvZfsO9VhnKErTDYcuWLbS3t7Nw4UISiQRr1qxhw4ZgjcWGDRtYu9Z5B7nyyit57LHHUFU2bNjAmjVrSCaTLFiwgPb2drZs2eJdExh0izjWAR8Ux5RbiRMIAB4EPgSgqo+rqpm5+BSOigZARN4OnAL8dFT+ECzjlloPFFXVEarqczglrqX2z/f9vhX4pO/zA8ADBcf34syTCLvWAPD/VPNc1ZIZyJCckiR1zOkG663hEGJmFyoKKB7kks3JQNXTiASKnuJAcfT1o0w9fWroOYHUU7z2zexR9SiAjo4O5s3LZznb2tp4+umnSx4Ti8WYMmUKXV1ddHR0cOGFFwbO7ejoAAhcE0c5X4BTXHFUVTO+7f4iDcPVwCMAIhIB/h7Hi7uk3HcZSqGGZWJQ62b2hG4z3tfVR8/+HjIDGeqm1Hnbw1JP/nUqVDVvZvuMYnNMojlRpChOZMJdmKL4/bbfc/f8u9m/dX/oOQEzexwoitH2KMKyk4XVeKWOGcp2nMKKigUXIvJRnJerO9xN1wD/pqp7C08supDqN1R1uaounzlzZqXDLROACaEoxisP/dFDJBoTZFNZ6qbWceyNY0B46smfXkr3pkEh2ZIkm84WLXaUbHEUhQkOiWZHUbz22GskW5LMPT/s5bI0YYGia2cXAIdeOcSc5XOKzvErimg8WvNmtn8exWjQ1tbG3r35MXjfvn3MmTMn9Ji2tjYymQzHjh1j2rRpZc/1bydfjHEImCoiMVdVeEUaACLyXuBG4A9U1SybeBHwLhG5BmgCEiJyXFVPOLVqGf/UeqCY0Iqiflo9/Yf7HUUxNa8oQquefKrBLFhUZGan86knv6JINifJDmbZ9PlN/OKWXwzpGXOZHJrV4mVY3Tbnx39/POy04MzscVAea/6sRyugnX/++ezcuZPdu3czODjIunXrWLVqVeCYVatW8eCDDwKwfv16Vq5ciYiwatUq1q1bRyqVYvfu3ezcuZMVK1Z418QZ1BPAGmCjW1zxOE6xBTjFFxsARORc4D5glaoe9L6/6kdU9TQ3TfsF4J9tkLAYbKAYQ+pb3UCRcjwKg+dRlDCz/YEiEouAOuaxOT7RnAh4FPHGONlUlv6u/qIBvxJGlQweHwykOszCST37e0LPKzKzx4lHMVoBLRaLcc8993DZZZexZMkSVq9ezbJly7jpppvYuHEjAFdffTVdXV20t7dz5513eiW0y5YtY/Xq1SxdupTLL7+ce++9l2g06l0TWAS8BHxfVbe7t7wBuN4tupiOU4QBTqqpCXhYRJ4TkY2j8oUtE4paDxQTOvVUN62O/sP9ROIREo0JL5dfycwuChTudhNMki2uokhliSaixJIxsoNZ+o/0D7l6yZsMqE4lVbzB8U/MehglA0VB6mm8KIrRDGhXXHEFV1xxRWDbLbfc4v1eV1fHww8/HHrujTfeyI033hh6TeBFVQ0Uc6jqa+Tn/vi3v7fSc6rq/wH+T6XjLJOHWg8UE1tRTKsn1Z0i3ZsmVhfzvIlK5bGBQBGPeMeGVT1FE1GiiSip7hTZVHb4gQIC5xpFUSn1ZBTFuPEoajygWSxjga16GkPqW50V2XoP9hJNRj0lUVj1pKoVFUUuk/OOSbQ4VU+ZVIZo0gkURgGcSKDwp62MR1GNohgP5bGj7VFYLOOZWlcUEzr1VD/NCRQm3WQCRaGZXWhqZ/qdv6lAoEgHFQXAYM+goyiSUW9mdrq3oPlcBSopip7f93jLs/opbDNe62/qVlFYLKWp9UAxoRVFXWu+0imajHpKojD1VFgmW1j1ZI7xexQAqWMpL/VkKDSlKxEWKFTVUUGJKOnedOhkvMI247X+pn4yPAqLZbxiA8UYYhQFEFAUhakn/yDrTz0lmhPB1JN7vCm17evqKwoUuUxuSLO0A4HCDQgDRwfIDmaZ9dZZgKMqCilqM17jb+pWUVgspbGBYgwJBIqkz8wuqHryv+UaRRGrjxGNRwNVT2aQazq1CYDuvd3EkjGiyWB76qH4FGGKwqSdZp/rNOP1+xSHdx2m45mO4jbjQ3xT3/vrvfzkmp8MSf2cCNajsFhKY83sMcSY2RBUFIWppzBFYdJLgaqndI5IPELzqc0AdHd0FykKGJpPERYojJF96rmnOp99lU9P3PwEG/9s4wkrilc2vsLWr289aQsuWUVhsZTGKIpYzAaKk06hR1Eq9RSmKLxAUZB6isQinqLQrIYGiqEoCv9AbaqeTAWVURT/8dX/4J4z7yGbzpLuS5PuTxfNzB7qm/rA0QHAaZd+MrAehcVSGhMoEgkbKE460XiURFMCcBSFCRAmVRTWqK5IUfiqnrLpLNF4lKZTmvL3cCfc+Rmp1NP0M6YTb4hz4PkDdL3SRbo37SmbatbM3v/sfh75/COh6aWBI06gMBVeYfzu0d+R7huZQGIVhcVSGn+gyNZgdnZCBwrI+xSxpJN6isQiAZUAwdRToaLwVz0ZRRFNRGmY0eDsT4Yoit4TCxTHDxxHokL9tHqmLsi3GTdBwvSHgvJrZr/0ry+x5R+3hAYuT1GUCATHDxznXy79F7Z/f3vo/qFiPQqLpTRWUYwxXqCoCwkUYWZ2xukea1ppFE64M55F02xHVZxo6qmUR9E4qxGJCB/+vx/mPbe+B8gb6rlMrqo1s/sOOevnmCouP/1H+oHSqSdTgTXU3lWlsIrCYimNEf3xuA0UY4LxKaLJKLH6GJF4eUWRTWfJDGS8NFVh1ZP5bHwKf6BoPKURGF6gSLYkvcF5sGfQWz+jdUGrF5S8IBGiKMLe1Ps6SwcKoyhKpZ5Ms8KRMrvD/CCLxeJQ64piQs/MhqCiWPInS6ifXk8kGgwUhWZ2uj/tVUbavzUKAAAgAElEQVQVVj2ZVJSpfDIzswFa2lroPdA7rEDRMKPBOy+bygZKbr1ncH0Sv6Iot2a2URRhE/aMR1FKUZgAUW5OSHYwi6oWeTRhDGfhonR/mmgi6v19WSwTFX+g6Osrf+xYMOH/DzSKIpaMsfC9C1l560pPFYTlzY2iMBVSYVVPkFcUsWTMUxRT5k0BypfH5rI59jyxx0vpZAYyIE5AM4Eik8oEBt/CZ8hlcqFrZhea1r2djileqChU1Us9VVIU5Vbu+7+f+r+sv2p9yf2F3xuG5lH807J/4ul/fLrygRbLOKfWFcWEDxR+RWEoTD0VtvAIDRTu23xhoIgkIl6gaJnXApROPR157Qj3LrmXB9/zINu+uQ3Au1eiOeG9+RcqCqNi/B5FYVNACPasgtIeRbo37R1bSlEYpVNOUXTv6+bo7qMl9/sZjqLo3ttN997uqo+3WMYrEyJQiMhUEVkvIi+LyEsicpFv3xdEREVkRolz14rITvdnbcj+jSLyou/zOSLylLvoy1YRKer5PxRMoPAPvBJ1GuyFpZ4KFUVR1ZM7KPtTT+btv2FmA9FEtGSg2LF+B4d3HgZ8HoEJFE2JoKIoEdhCzeyCwAfOG3z/YUc1FBrSRk1AaUXhpZ7KeBS5TK7qeRhDXQpVVQNtUyyWiUytm9nVehR3A5tU9Up3ScgGABGZB7wPeCPsJBGZBnwJZ5F5BZ4VkY2qesTd/ydA4YILXwX+RlUfEZEr3M/vHtK38mFmZ4emckLSIblBp3us51FUSD35zez61vrAgF9I36E+YnUxVNUbgE1Q8J+XTWWJTS8RKNw5FGYANQsXme9hAkz/4X7nT5xiRWGCFJRRFKnKisLfabcSQ1UUYYUGFstEZdwrChFpAS7GXepRVQdV1eQb7gK+iDckFXEZ8KiqHnaDw6PA5e51m4DrgS8XnKNAi/v7FHyL1g+HM95/Buf/+flMa5/mbStKPfnecs28Ai/1FPdVPYWY2X6Poq61jkRToqRH0Xeoj/rp9cSSsXxqZyDrpZ4838Jd58J7Xp+Z7Q2gbqAxM7P93wfyFU8QEiiO+AJFiXkU5vnKeRS5TK7qCXlD9SjM34lVFJbJQK0HimoUxUKgE/iWiLwNeBb4PHAJ0KGqzxeuleBjLrDX93mfuw3gVuDvgUKP/78Bm0XkaziB7B1hFxaRTwGfAjjttNNKPnzL3Bau+P+Cy2OaKpowM9sM1tWa2dFElOY5zUhEnJnUjfGSiqK/q5+GGQ1kB7N5s3jAMa4DqaeB8mY25N/0A6knX8AzRjYUVz35FUWl1FNusPRAPZTU01AVhfk70czJaVposYwltR4oqvEoYsB5wNdV9VygF7gZuBG4qcK5YRFEReQcoF1Vfxiy/zPAdao6D7iO/KL1wYuofkNVl6vq8pkzZ1bxNfKUNLMlP6gWzqPwzGz37T3RmOAP7/lDzv7o2bQubOUvDv0Fc1fMrZh6apjeQKwulk89+TyKdG8azWlZM9sMoCbQ+FNPAUVxqLSi8HsUlVJPlRRFpj9TVQfaoXoUNvVkmUxMhECxD9inqqZOcT1O4FgAPC8ie4A2YJuIzA45d57vcxtOKuki4O3uub8CFonIE+4xa4EfuL8/TMgC9idKqdRTvCHuDaolzexY/o9sxbUrmL5oOpD3QsoGiq4+GmY0EEuGBwpw2n8UpZ7CFEWqWFH4B1WTeorVxcp6FBXN7Aoehf/YcgzZo7CpJ8skwm9mqwbXp6gFKgYKVX0T2Csii91NlwDbVHWWqs5X1fk4AeE891g/m4FLRaRVRFqBS4HNqvp1VZ3jnvtO4FVVfbd7zn7gD9zfVwI7h//1wvGqngry5vGGePnUk8+jKEWiKVGy15PxKKLJaN4DcAOFaRmS7ks7ZrY/9RQvDhR+RRHqUbiKYuqCqcWpJ9ejiDfGK5fHVqh6Ms9ciaF6FOY4GygskwG/ooDaUxXVVj19FviOW/H0GvCJUgeKyHLg06r6SVU9LCK3As+4u29R1cMV7vVfgLtFJAYM4PoQI4mIIBEJVRRmUC0MFIUtPEqRaAxXFLlsjoEjA56i8HsU9dPqvVRXZiBTWlGkc96zBszsEh5FsiVJw4yG0NRTsiVJvCFeuYVHFYoi3Z+mnvqSx4FvffIqPQdPUdiWH5ZJQFigML/XAlUFClV9DqfEtdT++b7ftwKf9H1+AHigzLl7gLN8n38FvL2a5zoRJCr0Hujl11/7tfc2H2+Ie6vJhbXw8HsUpYg3hZvZA0cH0Jw6VU8hHoW5X6Y/4yiKMvMoID+QmzbjEHxb7z/kGOfJlmRg4SOA1NEUda11SEQqpp4qeRTmmcthZpEXPmM5rKKwTCYmiqKYcERiEV747guke9Os+Jxjg8Tr494bbKWqp1KU8ij6uxwDuWFGg5N68imKaDLqKYqBY05ayJ96KpyZDT5FEZXQCXe9nb00zGwg2Zyk69Wu4LMc6ae+tZ7sYPaE51FA5dSTSTsVPmPZc9JDS1VZLOOZWg8UE76FRykisYg338Hk7M1bPYQEinT1HkW6N11UCWQ8g4bpDYF5FGbCnbm3MZpLmdlm4MymsiBOGs0/z8K7X6djnCdaEqFmdt3UOmL1sYrzKKryKCqUyPpbiwy16skqCstkwAaKGsXfkdQzd90UFFRX9RRGojGB5jSwzgQ4FU+QVxSFqSdPURwtVhT+QGAG3Uwq432HUoqicWYjyZZk6IS7utY64vWlPYqhVD1VSj35FYVNPVksxfirnsAGiprBP+Cbnkj+QGEGbn9fqFwmh8RKTi4EINHsvBIUDs6eoggxs6tVFP7gk01lkYjzLIUeharSe7CXxlMaSTYnyfRnvAFXVen5fY/jldTHTqjNeLWpp4CiGGp5rDWzLZMAqyhqlECgcCegmeAAeUUhIkhUvMlulVJPzXOc1h7d+4JdT41HUdLMrgsGijCPwj+oZ1IZL4gVlscOHB0gl845gcJd0tWU/R566RD9Xf3Mu2heWUVRbQuPwucqdxxUP/BbRWGZTNhAUaOYQRacVEwkFglUNPmrjqLxaNWpp6mnO2tcH3v9WGB736E+ookoiaaEZ2ab5oBhqadQReEb1LOD2eLUkzsI9x5w2nc0zvIFClfhvPbYawAsWLmAeEOZeRRDMLOHknqyZrbFUowJFCb1lK6uM85JY9IGCv+AP3B0wFkitUSgMAsD+dfMLsXU+U6gOPp6cJ2Gvi5nsp2IeBPujKoISz2FlccWpZ6iwdSTGYSPH3DKYZtOafJSYWZ+yJ6f7WHqgqlMnT+VWH3shNuMw9BST9ajsFiKKVQU2Rp7P7KBAmcAjsQigbSSvwIqEot4nVsrKQrTQfbonmCgMPMaAK+Fhxn4A+WxR0qb2YWpp0JFYQbX3oOuojglqCjM6noLLlngfcfhKgpVrbj4kWFYisJWPVkmEYVmdq0Fisk7j6JgHeZoPOoNuP7ZzuAM1KY0tZJHISJMOX1Kceqpy2kICI5ayKQyXqCo2szuDzezC8tjTeqp6ZQmb05HqjvFgecPMHB0gAUrnUBxIh6FXyVUnHA3nPJYa2ZbJhFGUcTcEbnWAoVVFOazL/UUq4vhb53upZ6qUBTgpJ8KA0XvQWcCHDhBQLPqDeLVmtn+1FPAzC4ojz1+4DgSEeqn15NszpvZ3R2OwT79DKeRoZlHEdb91aScNKsBRWDwv+mPxoQ7m3qyTCZs6qlGMYNsvNHRetF41BuQ/f6A2ZdNZUGp6FEATDl9SsCjUFW693bT0uasx2SCgL9TrYg4nV6POdsCS7dGBKS0mV1YHtt7oJeGGQ1EopFA6skM/ubaJt0V5kP4lURY+ikQKIYw4W6oCxdZM9syGSg0s23VU40QiUWI1cWYMm+K89mvKOpjRceawbAqRXH6VAaODHiBoP9wP+m+NC3znEBhBmqvXYcbmGL1sVBFUfgMEDSzCxWFmUMB+UA4eHzQG/zNtb2OtSEDfcA4dwPF67943QuA/kBRddWTWEVhsYRRGCisoqgRIrEIzXObvaqgcooiEot4g2EljwIcRQH5yqfuvU7KZ8ppUwLXN+rBfI7Xx0M9CnNf/4AcMLNDPIqmU5oC186msoEqKyDQiLAQv8owvz+8+mF+fcevnXsNIfVkFEUsGbMtPCyWEGrdzJ60gSJWF6OlrcVbMKjQo/ATiQ9RUcwPzqU4ttf5r1Ev5o3emxHupoBi9fkeUFUpikhpj8IoCnOdTCrjKYrC1FOookhlvOsbRTFwdMDrjzUcRRGri5HL5Hj5Ry/z0g9fKn+ONbMtk4haTz1N2qqny+68jEgswuM3PQ4QKI8NVRTuAF6NR2Em3RUqisLUk1nX2vgIYTPDvWeIRwLpoFwml/dZ6vOLHoGjKBpnNXrPLlEJzttIBhWFWYLVBAZwAlGyJcnA0QEyqQy5bM5RJYPFKaFqPYpYXYxsOsuv7/g1mlOW/PGSkufY1JNlMmFTTzXKnOVzmH3ObE9R+Mtj/QM2BFNP1SiKxlMaiSaiHHvDVRRvHCMSj+TTQe5Abfo/mfRXYDZ4QerJ/wzeNjf1FG+MgziVTYO9g6T70p6iMPfLprIlFcUPPvoDvnPFdwLXzgxkvOfKDma9IGSuMZyqp2jSmeGe6k6VXC7WO2cYZvamTZtYvHgx7e3t3H777UX7U6kUV111Fe3t7VxwwQXs2bPH23fbbbfR3t7O4sWL2bx5c+CawFkisktE/tJsF5EFIvK0iOwUke+5i3ohIteLyA4R+a2IPCYip7vbzxGRJ0Vku7vvqqq/mGXCY6ueapxqUk/ReHRIqScRoaWthZ59ziJI3Xu7aZnbkm/i5w7UZl1roygCbc6TpZ/Bu4+rKESEZEuSwZ7BwBwK71x3JnhhWsvc7+ALB3njl294CwypKplUxnuubCrrpZyMKhlK6smvKHLp6gKF1+Awq6Hlu0XHZ7Nce+21PPLII+zYsYOHHnqIHTt2BI65//77aW1tZdeuXVx33XXccMMNAOzYsYN169axfft2Nm3axDXXXEM2m/WuCbwKLAU+LCJL3ct9BbhLVc8AjgBXu9t/AyxX1bNx1pf/qru9D/jPqroMuBz4BxGZWvGLWSYFtZ56soGiaeTNbICWthavMeCxvcc8I9t/fS9QNBennqKJ6hWFuUaqO+W17wgoCneCXzaVdVJRkWDKChxVEKho0nwAyw5mvXXAh5N68jyKZGzIigKC5bWl2LJlC+3t7SxcuJBEIsGaNWvYsGFD4JgNGzawdu1aAK688koee+wxfvyZH/MP/+0fWLNmDclkkgULFtDe3s6WLVu8awKDqjoIrAM+KM4km5U4gQDgQeBDAKr6uKr2udufAtrc7a+q6k739/3AQWBmxS9mmRRYM7vGqcrM9nsUVSgKKAgUbxzz/AkIpp4kIt6bvX/5Vb9fUPgMBv8xZt0Jfztz//1M6smf0vK3VQfo3N4J5FWDCRSZVMZTFMNJPRV6FKmelNfNthT+61eTfuro6GDevHne57a2Njo6OkoeE4vFmDJlCtv/fTt7Xt0Tem7hNYF9wFxgOnBUVTMF2wu5GnikcKOIrAASwO/CvouIfEpEtorI1s7Ozgrf3DIRsB5FjROqKArnUfirnqowswGa25rp3tdNLpOjp6MnECj8ZnayJenNAveqn5LFNQaFZjYEO+CaQGHKa+tb6719sbqYZ2b7r22+Z9OpTprq4PaDQH4OhVE65RRFojlRpHReeOiFgGLwexSadXpEZVPZsgHAv68aQzssPeWfXV/qmEx/JnTmuYiUSnkpELYoSeBgEfkozjrzdxRsPxX4NvAJVQ39Yqr6DVVdrqrLZ860omMyMCFSTyIyVUTWi8jLIvKSiFzk2/cFEVERmVHi3LWu4bdTRNaG7N8oIi8WbPusiLziGn9fLTxnJPEURayCohiCmQ2OosgOZjn44kFymZxXGgtBRWEMY8gP3IVGtrlvYYonkHoygcJtKlg3tc7bZ1bUK1IUbmBa9EeLaJ7T7CkKoxoSLa6ZXcajSDYnA8/V9WoXP/h/fxAof/UrCj/l0k/+1FM1gaKtrY29e/d6n/ft28ecOXNKHpPJZDh27BjxgTit8dbQcwuviZNG2g8cAqaKSKxgOwAi8l7gRmCVqqZ821uAnwB/papPVfxSlknDRFEUdwObVPVM4G3ASwAiMg94H/BG2EkiMg34EnABsAL4koi0+vb/CXC84Jz3AB8EznaNv68N5QsNlUDqKVY6UJg3adPYrxKmXcfrv3wdINSjGOwZ9NI7kA8UYYoiGo8W5erLKQp/oDAr6hUqisZTGjntXafxtv/8NmYum1ky9VRJUfhTTz37HQPfrzLMsWGB4j/u+A86tgRTRFCgKKqYS3H++eezc+dOdu/ezeDgIOvWrWPVqlWBY1atWsWDDz4IwPr161m5ciWZ/gxnTz2bdevWkUql2L17Nzt37mTFihXeNYGEW9W0BtiojtR4HLjSvfRaYAOAiJwL3IcTJA6ae7vn/xD4Z1V9uOIXskwqcjkQgaj7HjfuAoX7FnQxcD+Aqg6qqmlkdBfwRQpkt4/LgEdV9bCqHgEexan4QESagOuBLxec8xngdvMm5v+fbTSoxsw22yUqnPr2U6u6rlEQL//gZYDAef63epPeAV/qqS4k9RSiZPyKItGSYLBnkIGjAySaEoHj/akn/71jyRif+MUnOO0/ncass2bR+VJnYL1vf+qplEeRbEkGgsLxN524HxjosyUCRc8gP/ufP+OF775Q9N2GqihisRj33HMPl112GUuWLGH16tUsW7aMm266iY0bNwJw9dVX09XVRXt7O3feeSe33XYb6b40s2OzWb16NUuXLuXyyy/n3nvvJRqNetcEFuG8HH1fVbe7t7wBuF5EduF4Fve72+8AmoCHReQ5Ednobl+N8//Rx93tz4nIORW/mGVSoAqRSL57bGHq6eGH4Uc/yn9+6ilw/mmeHKqZcLcQ6AS+JSJvA54FPg9cAnSo6vOFuWAfcwG/dvebfrcCf49TNuhnEfAuEflbYAD4gqo+U8VzDotQMzuk1xPAKWefQqIxQTUYRbHn585CQc2nNnv7/G/1Q0k9FRJmZg8cGaCutS5wXDQZZbDH6fUUplYAZi6bSaY/w5HdR7xg4DezTfAoVBTJ5mSgBXvP7x1FEVa1VHjv428ed84NaTroDzTVzqW44ooruOKKKwLbbrnlFu/3uro6Hn44/zJvlFAunePGG2/kxhtvDL0m8KKqLvdvV9XXcFQyBdvfG/ZsqvovwL9U9UUsk45KiuKuu6CuDj70Iefzt78N3/0u/Pmfn5znqyb1FAPOA76uqucCvcDNODnYmyqcG2r6uW9S7ar6wxL3awUuBP4C+L6ERKKRqgyptjwWoO2itqqv2zir0TlPYd47ApUzQUXREqIoSpjZhQRST81JUj0p+g/3B9JO5nphisKPCWy9B3q91FNgwl0Jj8IcY1RFOUURrQve20xIDFvzQjO+NSxGaXa2CRS2Q61lrMnlHEVRKlBkMsFthZ9Hm2oCxT5gn6o+7X5ejxM4FgDPi8geHDNvm4jMDjnXP0oa0+8i4O3uub8CFonIE75zfqAOW4AcUGSUj1RlSLW9ngDmXRQc8MshEaF5rqMiCgOF//r+1JPZXq2iKDSzUeje110cKMxCSWUUhVFKg72DRYoim8p7FEWpJ/f5jaHd+6Yz4c+vEkopCtMDK6zN+VCrnoaDX1FYLGOJCRSlUk+ZTHBb4efRpmKgUNU3gb0istjddAmwTVVnqep8VZ2PM7if5x7rZzNwqYi0uib2pcBmVf26qs5xz30n8Kqqvts950c4k5kQkUU49eaHTuRLlsO8EUfi+V5PYS08YGiKAvJv6UWBwp96ailOPZUyswspNLPBeUv3l8ZCvuqpnKIw7cjTvem8R9FS7FEUmdkt4Yoi4DGU8ChMD6zQ9S7854/SQO4pihLLvVosJ4tqFEVNBwqXzwLfEZHfAucAf1fqQBFZLiLfBFDVwzhexDPuzy3utnI8ACx0S2bXAWu1mh4Ow6Sa8timU5uYumAqrQtbi84vx5R5U4g3xpl11qzAdv9Sq2Fm9rAVBU7JbaiiGKheUYROuOsrXR4L+UE3LPVkFEXh9zKpp7FWFDb1ZBlraj1QVNU9VlWfw5k8VGr/fN/vW4FP+j4/gDP4lzp3D3CW7/Mg8NFqnmskCGsKWBgo/uCv/4B3/Pd3FE3gqsS7/updnP2xs0MHedMgL8zMruRRSFTQrBaZ2d7vU5OBc6PJqFceW42iMO1Dwibc5TI5NKfe4G2MczPT2gsUg8UeRSlFEeZR+FVEqYH8yTufZPv3t/PJpz4Zur8SNvVkqRVUHTO71JrZYYFCNR9gRptJPzM7VhcjmowSb4wz9XRHNRQqgGgiWvSWXg2zls3ijCvOCL+vGwxCzewK5bHmuLDUE1CUejJmdtUehZt6Ml1p/RPuwAkCJlCYduYDRwbIZXJe6/RyVU8muHiKosJSq6UUxaFXDnHg+QOh+6rBKgpLrVCoKKrxKMKOGy0m7XoUBhHhYz/9GDPOnEHDjAY+97vPnZT7mmAQMLOrLI+N1cUYPD4YnEfhUyZhqaeheBTZ5vxKeLFkLOBRQEGgmOkEiv7D/fQe7PVm1JSbR1HfWu8Y5O7M7OGmnnKDOTIDGXKZXNUz5v1YRWGpFYaTejL/TVRXsX9CTHpFAXD6xad7b8YnCzNghymKsMHcb2abAbeUogibR5HL5Ej3p0sGimg8SiQeCVQ9xZIxogknbWVST+Ckiszg3TDTmanef6TfSztBeNWT/zv7A1tJM1t8v4dgzqvUibYU1sy21AqFVU9DCRQnAxsoxgiThqnWo5CYO2pKfsANM7MhRFG410t1p0qmnsBJP6V7094bfjQZdSqmqlAUA0cGAoGiXNVTsiXpeUMQ7lFk01kvcJZSFCMWKGzqyTLG1HrqyQaKMcJ7u66y6skoikgs35MqYGY3lwkU7gBdLvUETttxv0dhFIV/HoW5jhm84w1x4o1x+g/nFUUkHinrURQGirDUUy6d8wJnqYHcBIpKLctL4fWoUkI7yFosJwvTwkPE+ak1RTHpPYqxwv927W0rV/XkBodAoPClnqKJqFcGGzaPovC+YcQb44F5FNFENOBRmGorf+opEotQP60+oChM51xDJUXhP/alH76ERMRTFP30j5qi8Ae/XDoXUGgWy8nEtPAAR1XYQGEBwlNPZedRuOWx/jLewoEt2ZIkM5ApqSj89w3DpJ4Gjg2QnJJEIhJQFPWt9fQd6gukniKxCPWt9fQf6adnfw91U+tINifLzqNItCQCCsifenrya0+COOkmEzgrBoqeE0s9mWuVC6IWy2jiL3ONxWzqyeISlnoyA9VwFAXk1Umhme2/XtnUU6OTekodTXnBxu9RmOv6U0+RWIS61jr6DzuBonluc1HqaSiKIpt2qqFy6Zy3Al//4X7++ZJ/puvVrsDzjljqCetTWMYWf6CoRUVhA8UYEUvGQPJlqQDJKUkuvP5CFn1gUdHxoYGiYLnURHMCiUhgEIaC1FM1iuLoQD5Q+Kqe6qc5Ka0iReGmnno6emie00w0Hg1VFCUDhc+jyKVzDB4fDJjZnTs62f2z3bz+i9cDzztSZra5r8UyVthAYQklVhcj2ZwMzPYWES77+8s45exTio73zOx4eUVRN7WuaAa5P6VSjaLwB4pYMkbqWAoUL1AUehR1rXX0H+mnu6OblrktTrqqkkfRnG+d4k89hSmK1DFHMZjJfN6xJ5h6yvQF72uxjBXGzIbi1FMu5+y3gWISEquPkZySrHygS5iiCPMowmaQB9bJrkJR9B/pDyiKwnW4/YpCokL9NMe7OP7mcZrmNBWnnnwVUgB1U+o8RdF4SiO5dM5bnzo7mGWwx1EUxqPwAsXBEoHCKgrLOKecmR0WFGygmCS84y/ewQfu+0DVxxszu5xHccHnL+Ddt7y76Fy/iqikKNJ9TurJBIV4Q9xbjKhuWtCjkKggIt5Ma82qoyhKpJ6mL5rO+7/+fs780JleoGg6pcm5pulKm86R7nPmchgFkup2AkXfweAaVyPqUdhJd5ZR4umn4e9KtlF1KJd6MsEgl8uvrV0uUPz853DnnSf2zIXYQDFGnPLWUzjjD8P7QIVhgkO5qqeFlyzk7I+cXXRutVVP/tSTaSx42rtO897oCxWFeQ6/ed48pzk89SROam35p5cHUk9Ns91A4foUJsCkulOeAhk45iiaIkWRHjlFYVNPltHi4Yfhb/6m/DHlqp78v5sAUi5QfPe7lQPTULGBYpxQjZldimqrnkzqabBn0Es9nfmhM739hR6FeQ6zHQitetKsFgU1L/U025nZ7VcUAJrT6lNPI1Aea1NPltEinXZ+ylGNovD/Xi5QVHO/oWIDxTjBPzPb/F6YeirFUBSFwQSK6YumM2OJs8BgYXmsFyh8E/zCqp5y2VzRs87/g/ks+dMlnnFvDG3/eZ6Z3T06Zna6L11x9rfFcqKk044ZXW7pUr+ZbQOFZdhUY2aXolqPwrQah2AbEKMqSqWejKKQiNB0SlNR6ilMUbQubGX1+tXUTanzrgnBN3tTHmtST32dfWguv4bVSMzMLry/xTLSmEG73ODtN7PLpZ5soLCUxTOzy5THlqLaqqcwRQFw7tXn0v6H7cw+x1kSvTD1ZJRG4ymN3kqBhRPuSj2rCVyFHgXklZBZZjWXyXkVWDAyZrapPLOpJ8toUW2gGElFYRY2GilsoBgnnIiiqHYehV9R+NNJ094yjY/820e8luJFisI9tmWus0Z4JB4pqnoq9axmNT2TevIP2NFEtMiHMT6Fqg5JUWhO6TsUrJpK96W9gGhTT5bRYiwCRal9w8UGinFCpe6xZc+tcmZ2KUXhXSeRf/v3B4rklCSI40+Y4wqrnkopCvM82cEsmtNAaikSjwSWgAVfoMiqt0hSNR7Fyz96mbtOu8tTJBj6L0MAAB60SURBVKrqBAo39WQVhWW0GGqgiMVGJlCMZPrJBopxgr881qxNMZzU03A8Cu8ZohEkKkWKIhKN0Dynmdb2Vu8ZK1U9FT5PNpUteqv3lwIbjKHtD0TVKIpjbxwj05/xAkUunUOzmlcU1qOwjBLDURQn6lFUut9Qse0yxwknknqSiHi+QVlF0VBeUUC+91Ph8qMf//nHaZjhpKYKU09lPQqjUgazRYN1JO5UeKVJ0zirkd6DvZ6i8I6V6jyKdL/zf41JcZnSWONR2NSTZbSoZuAe6aqnSvcbKlWNNCIyVUTWi8jLIvKSiFzk2/cFEVERmVHi3LUistP9WRuyf6OIvBiyvex1JxvVzMwuhwkQlWZmA6GNBf3XKUw9geNjmDSOURSmLUc5RWGeK5PKFKV//N91yulTAIoCRX1rPYPHB717lcIY4sY0LwwUNvVkGS2GWvVUKVCEzdAe6v2GSrWpp7uBTap6JvA24CUAEZkHvA94I+wkEZkGfAm4AFgBfElEWn37/wQ4HnJe2etORjwVER+6ooDyLcwNJvVk1qIIw7QdLwwUgWNclWB6PGlWKx5bMvXkBsi6KXXUT6svDhTT60GDk+fCKKUovPJYqygso8RwPIpyqadSQWQo9xsqFUcaEWkBLgbuB1DVQVU96u6+C/ginq1YxGXAo6p6WFWPAI8Cl7vXbQKuB74ccl6l6046TsTMhrySqEZRFK6QF7iOu5BRuUBhBnfzll5VeexgtlhR+IJivCFOw8wGr9+TFyjcORyVDG1PUQwGFYVJsVlFYRktRrLqKZstHUSGcr+hUs0r6UKgE/iWiPxGRL4pIo0isgroUNXny5w7F9jr+7zP3QZwK/D3QKBmscrrIiKfEpGtIrK1s7Oziq8xvqlm4aJymPUvSg3ukFcUpfwJc52KisINauYtvdrUUzkzO94Yp3lOM8f2Hgtc2wsUFQxtoyhM6slM4vOvsWGxjAYjXR5bq4EiBpwHfF1VzwV6gZuBG4GbKpwbNpKpiJwDtKvqDwMHizRUeV1U9RuqulxVl8+cObPytxjnVLMUajlidTFiyVjRWhWBY+qdYFIuUJQyswuPAd9s62rM7FS4ojBBJ94QZ8aSGRx66VBgDkXDdMdAr2RoG0VhUk99nc77SfNcp6TXpp4so8VQzexKqadaDRT7gH2q+rT7eT1O4FgAPC8ie4A2YJuIzA45d57vcxuwH7gIeLt77q+ARSLyBPCWKq876fBUREyGpSiiyWjZtBM43V3jDfHygaIKj6Iw9VRVeexgsUfhV0/xxjizls0i1Z2ip6Mn6FFQWVEUmtmmzNbM/bCpJ8toMdJm9lgEiorlsar6pojsFZHFqvoKcAmwTVUvMce4g/pyVT1UcPpm4O98BvalwP9Q1cPA191z5wM/VtV3u8fMquK6k44TKY+FvKKoRMP0BhpmNZTc7/co/DO+A8cUpJ7M2hWhz1Wm6slvZscb4sxc6ijHzh2dXpvyaj0KL/XkBhhPUZxqFYVldJksqSeAzwLfEZHfAucAJbudi8hyEfkmgBsQbgWecX9ucbdZhogZfKPxaL577BDM7FgyVnJg97Nmwxre/aV3l71OtVVP/tRTpRYefkVhtvnN7ERjgpnLnEBxcPtB79rTF00HgY5nOsp+r8LUU29nL8kpSc/Atx6FZbQY6aqnmg0Uqvqc6wecraofciuY/Pvnm7d+Vd2qqp/07XtAVdvdn2+FXHuPqp5V4r7zrZpwOFEzu5rUE8Dsc2Z7iwmVuk4ljyIs9VRNU0BzvFEJATO7IU7jzEYaZjbQuaPTG9hb5rVw+sWns+P7O8p+r0Izu+9gH40zGxFxUnk29WQZLSaTorCMMWET7oaSekq2JEk2V79GdymqKY8tSj2VURSRaASJiFP1VFDyGjCz3Tf/mUtn0rk9HyiiiSjLVi+jc0cnB7cfBKBrZxeZgeD/QWGKwjQ5LJxJbrGMJCM9M9sGCktJwibcDUVRvPf29/LBb33whJ9jOKmncooC8gZ5YclrwMx224vMXDbTURSpfKBY8idLkIiw/fvbUVW+8fZv8NMv/DRwjzCPonGms7peYW8qi2UkGen1KGygsJTkRM3s1oWt3mpyJ0I15bFhE+7KPavXFsQ93qxv4TezzRyPmUtmkjqW4tgbx7znaZrdxOxzZ7PvyX3eUq7PP/i8tzIehFc9GUURTUStorCMGjb1ZDlpnOjM7BF7jmpaeIRMuCurKBIFiqI1n3oqVBSNsxwVcPzN49654FRrpbpT3nyKweODPP/t/JxNk4rKpDKoOmtTBFJP1sy2jBInM1D4+0DZQDEJOVEze6SoyqMYQtUTuMHHryim5RVFoUdhymL7uvq8Y8DxYH6z/zec+45zuZu7+SW/ZNv/3ubdI92fJkOGm793M+1vaee+9H10R7u9azy87WHa29tZvHgxmzdv9s7btGkTwFkisktE/tJsF5EFIvK02+zyeyKScLdfLyI7ROS3IvKYiJzuO6dsg0zLxGSk16MoFyj897CBYhJiBt9oYngzs0fsOYY54a5cUIslY4EWHotXLebC6y6k9S2tgfJYwDPkBw47LTi8P5fGKN/b/z2+/Q/f5lqu5aX4S7y6+1Xn/qpk+jNsYxuN8Ua2bN7ChVzIfY/eB8BBPcgvX/sl27dvZ9OmTVxzzTVks1my2SzXXnstwKvAUuDDIrLUfeyvAHep6hnAEeBqd/tvcOb+nI0zOfWrULlBpmViojo8M3u4HoUNFJOcZEuSK/7pCs666qwxVRRmUB+pqifIp55MYJly2hQuu/MyItHi1FORonADxev9rzONaZw65VRixFgxcwXb+7c7z+H6Eq/wCivPWElfZx9LWcozLz+DqvLiwIu8o+0dJJNJFixYQHt7O1u2bGHLli20t7cDDKrqILAO+KA4fVBW4gQCgAeBDwGo6uOqavqXPYXTXQDKNMi0TFz8yuBkzMy2gcLC+Z85n5a2ljFXFJkBZxZ1xTbj/hYeZZoRmtRT4YQ7yKsTk3oyiqK/qz9w7LHsMZqyTV6zv1Omn8LRjNPk2FQ8ddPNtMQ0ejt7iRKlpbmFrq4uunPdtCbyL/dtbW10dHTQ0dHBvHn+DjReU8vpwFFVzRRsL+Rq4BH393INMgNMtoaXE5lqB+6R8ihsoLB4jKWZ3TizEc0qA0cHKqaeqmkKCL5KKjewGEUCVK0oovXOf43JnWhKgDrtQ0zFEzgqx6xpIVFxmiRG3DW4fYhIqcWQlBLNLgvO/yiwHLjDbKp0jrdxkjW8nMgMJ1CcSHnsaAUKuxTqOGQsU08t81oA0FyZxYiG0GYc8nMzzPEm0Ph/L/QojKIw++fOmUs33fR09ADQIz0000wmlfEURQstHDx6kL7OPrJk6entYdq0aUyvm86h3nwDgH379jFnzhwA9u71iwCvqeUhYKqIxFxVYbYDICLvxemC/Aeqamp09wHvLrjWEyX/UCwTAqsoLGPGWKaeWtpaip6jkMLUU0VFYVJPZrZ1oaKQ4MJLkZhTzhqJR7y26eeedS5ddLHrlV1kyPDL137JYhaTTWU9RbGYxTy+63F6O3t5NfkqK1euREQ4d+a5PPX7p0ilUuzevZudO3eyYsUKzj//fHbu3AmQcKua1gAb1ZEajwNXuo+5FtgAICLnAvcBq1T1oO9rbgYuFZFW18S+1N1mmcBUO3CP1MxsqygsHtMXTad1YSvT2qed9HtPmTfF+73a1FMlRVFoZvsVRTQeJdGY8AKCiJBoTjBwZCDgZTS2NnIFV3DTj28iRYo1K9Ywa+Msbr71Zs5sOxOAczmXRwce5RP3f4K4xnni9icAOK31NJZPX87SpUuJxWLce++9RKPOte+55x7e//73L8JZ/vcBVd3u3vIGYJ2IfBmn0ul+d/sdQBPwsPvMb6jqKlU9LCKmQSbYBpmTApt6sowZU+dP5XO/+9yY3LvxlEanid4Qq56GUh7rVxRvW/s2ZiyZETg+2ZwsChTJliSLWMS72t/Fkd1H+MM//kP+//bOPUiqOrvjnzPTPT0DDAMIgzMOCMMICmQRGBCixVoYjJLUuG5hZJOKZmNqq1Yxu27MSsoyS2XJruuWWlqbmLjqLkkZ0bBaQ0rFJT6SSpWKyCryWHkHGBGJD5CBeZ/8ce/tud307df0i57zqeqavr/7+P3unV//vvec83u0b2xn9V+u5tSRU/ySXxImzKrZq6geU82JXSdobm6O5nf9xOt5fsvz55Rt+fLlADtUtdWfrqoHcLq5Epf+e0H3qapPAU8FPgij7MhEKPy9nlSdj8i51oV/uz9unKgJhVESVFRWOEuSHj6ZWa+nDAbc+UWlcX4jjfMbY473Atp+ofDSTnWcIlIbiZmV1otReDPf9pzuifaiAseCsbmejHyQbYwCHBHwrItIBLq7Yy2K6mqLURgljBfQTrvXU5KFiyB2Cg9/3CEIL6Adb1GAE+Suqq2KWRDJi1FUj6mmv7ufns4ep1eUl3/Y5noy8kO2ricYFIG+PgiHBwfimVAY5wVenCJXrqfoGhe9AzGNfxBRi8LnovJPoR4ZHYku0tTXNdjrqXpMddSi8AuFWRRGvhiqRQGOGIRCg9ZFMYTCXE9GxtQ2OcuHBgmFVAhSIem7nnwWhb/xDyKZReHt97ueohZFXTXdX3Yz0DcQ7W7rz98wck22vZ6gtITCLAojY1JZFBDb+KayKMI1YXrP9DqjvcOpq2SiGIXXbdbb73c9+S2K/u5+ejt7CY+KjVGY68nIB9kEsxO5nkwojPMObyxFMqHwGt/Tx0/T82VPzBt/PFWjqpw3/66+tCyKREIhItE8IrWxrid/jCKR68kWLjLyRaq1Izxy5XpKN79MMaEwMiZVMBsGG983H3oTHVDmfnNu4LFew3/2s7NpWRSJXE8w6H6qqq1K2OspUhdxgtmne2JcT2ZRGPmiXGIUaQmFiIwRkQ0i8lsR2S0ii3377hYRFZHxAecmnYNfRDaKyA7f9k/dfLaLyAsiMiabGzPyx/hLx1P/O/XUz64PPKayqpLO451s/cetzLp5VtLBgd7b/dnPzmZtUfjTE/V6qghVEB4RpvtUNzqgsRaFxSiMPDEUoTgfXU+PAJtU9VJgDs4oVURkErAMOJzopFRz8IvI14HTcadtBma78/nvAf4m7bsxCkKkNsK3t3+bpkVNgcdUhCv4cOOH9JzuYfFfLQ48DgaFouvzrpxYFP5eT55FEaoJxQiCuZ6MQuA11pFI+sFsL0YxFIsiVX6ZkvJXKSKjgSW4UxSoao+qfuHufhj4PgGzYJJkDn4RGQV8D1jrP0FVf+2bvtk/n79xHlEZdhrlqlFVNMxtSHpsdKK/z4dmUXjX8fd68mIU4ZpwNA04Z8CduZ6MfOA11iNGZDYyG4YmFKnyy5R0LIpm4ATwCxH5jYg8ISIjRaQN6FDV95Ocm2wO/h8CDwJn4k/y8ecMzucfg83ZX9p4jfjEORNTTofudz3lKkYR73oK1YSiaf48wR2PoU7vLMPIJZkIRaYxikiktIQiBMwDHlPVuUAnsAZnGuW/TXFuwjn4ReRyoEVVXwg8UeReoA94OtF+m7O/tPEa/AvnXpjyWM9C6Dvbl9mAu4AYRaIpPOItivgYBWDuJyPnZCMU6XSPrax0RmuXklAcBY6q6tvu9gYc4ZgKvC8ih3DcQ9tEJL5VOAr4lwjz5u1fDMx3z/0fYLqIvOEd5Aa9/xD4Ew1YPcYobTwXUiq3EyR4u0+BZ1HEWx8JLYquQYsiZm6ouF5PgAW0jZyTL4vCv51NfpmSUihU9WPgiIjMcJOuAbapar2qTlHVKTiCMM891k/COfhV9TFVbXTPvQrYo6pXA4jIdThTOLf51h42zjO8Rjkti2LUuY120uODYhS+cRRSIVSEK6ID7sI14eSuJ7A4hZFz0m24Mx2ZXXJC4XIn8LSIbAcuB34UdKCItIrIEwDufPveHPzvkN4c/D8DaoHNIvKeiPxTmmU0SoiKcAUV4QrqZwV3ofXwz9OU7RQe4HM9uYIRioSiU3iEakKBridPnMz1ZOSafLmeCi0Uac31pKrv4az/G7R/iu/7VuAvfNtJ5+BX1UPAbN92SzplMkqbSG2EiV+ZmFbMIb4HUiqCLIqRE0YCUDOuBoBQtbPORe+ZXmouqImxKPx5zrttHnNumRNdl9swckWuej2NGJG5UOSyj49NCmjkhesevQ7tTy+8VFHpDIbrPdM7JIti1h/Nom5yHbWNzqSFlZFK+rr66D7VTXVddWyMIi6YnY6gGUam5DpG0d+fWihEcj+OwoTCyAvjpmW2TGvVqCp6z/SmZVFUhCqYes1UGubHBspD1SGmXD1lcNt1PXWf6qZqdFWs68kXzDaMfJFr15O3eFEyoQiHnY8JhVF2VI2qovOTzrQsCoBb/vOWlMd4K+d1n+p2Rmu7rif/TLOGkU+8xrqmJjfB7M7O4giF/VqMksCLO1RU5a5KhqpDdJ3sor+nn8joSNS95Hc7GUY+6e11Gv6qquCG21sfO1e9nkwojLLFa7zTtSjSIRQJceaE08M6MnpwEJ65nYxCkU7D7Y0Uy2Q9Cm97YMD5ZJJfNphQGCVB0CC6oVAZqaTzRKdzfZ/rySwKo1Ck03B7DX0qi8K/ZrYnFP7j0s0vG0wojJIgLxZFdYBFYUJhFAh/w93fP2g9+ElXKBJZFN7+RPmZUBhlh9d459KiCEVC0Wk5IrWDMQr/GArDyCf+htvbjscTj0zWozChMIYl0UF0ObQo/N1hzfVkFIN0hCLeokhnPQoTCmNYkheLonqw97e5noxikIlQZLIeRTpCoRobvxgKJhRGSVBIi8JcT0ahyMaiyJXrKSi/bDChMEqCaDA7h1Np+Od2snEURjEoluvJ25crobCR2UZJkA/Xk2dRSKUQqgmhAwoSO1utYeSToVgUQ3U9BeWXDSYURkkQnegvx91jwbEmRASpFFY8u4KmRbYMu1EYhtLrKVuhiERMKIwyJV/dY2FwfQqAWTfNytn1DSMVQ3E99fUNjrzORChGjbIYhVGm5DOY7RcKwygkQ+315FkVxXY9mVAYJUE+u8eaUBjFYqgxCk8E/ELR22tCYQxTLph+ATNvmsnkKyfn7JqJXE+GUUiG6nqKFwqAnh4LZhvDlHBNmJueuymn1zTXk1FshhrMTiQUXV1mURhGzjCLwig2uXY9gQmFYeQUi1EYxSabYHYq11PJCoWIjBGRDSLyWxHZLSKLffvuFhEVkfEB594qInvdz60J9m8UkR2+7XEistk9frOIjM3mxgzDXE9GsRluFsUjwCZVvRSYA+wGEJFJwDLgcKKTRGQc8APgCmAh8AN/wy8iXwdOx522GnhVVS8BXnW3DSMlmzZtYsaMGbS0tHD//fef43rq7u7m5ptvpqWlhSuuuIJDhw5Fz/3xj39MS0sLM2bM4JVXXom5JjBbRPaJSLQuishUEXnbfaF5VkSq3PQlIrJNRPpEZIW/fCLygIjsdF+2HhXx3iGNciUbofD+BglF/HZJCIWIjAaWAE8CqGqPqn7h7n4Y+D6QYDkOAH4f2Kyqn6nq58Bm4Dr3uqOA7wFr4865AVjnfl8HfC3tuzGGLf39/dxxxx28/PLL7Nq1i2eeeYYDxw4Ag0Lx5JNPMnbsWPbt28ddd93FPffcA8CuXbtYv349O3fuZNOmTdx+++309/dHrwnsAWYC3xCRmW6WPwEedl9oPgduc9MPA38G/Ju/fCLyu8CVwFeA2cAC4Kv5eRpGqZBNMBtiV7OD4gtFOr2emoETwC9EZA7wLvAd4BqgQ1XfT/JidBFwxLd91E0D+CHwIHAm7pyJqnoMQFWPiUh9oguLyLeAbwFMnpy7LpXG+cmWLVtoaWmhubkZgJUrV/LqW69STXV0MF97eztr1qwBYMWKFaxatQpVpb29nZUrVxKJRJg6dSotLS1s2bIFgJaWFg4cONCjqj0ish64QUR2A0uBP3azXwesAR5T1UMAIuJbyRhwXqaqgSpAgDBwPJt7PXwY5v4XdM3I5myjkJx5Fv7jIvjNRcDr8KcR+OaW2GMG1Nn395fBz7201+CnlfDwZ+6+mTDQ73wHeG4SvDHR2V4RgZB7zbMvwXOT4bUJzr4bIzD9Ndi+dGj3kY5QhIB5wJ2q+raIPILzo1gCXJvi3EQKoiJyOdCiqneJyJT0i+u7iOrjwOMAra2tQRaNMUzo6Ohg0qRJ0e2mpibeOvwWS/96KdOWTTvnmFAoRF1dHZ9++ikdHR0sWrQo5tyOjg6AmGvivOhcAVwAfKGqfb70i0iCqr4pIq8Dx3B+Fz9T1d3Z3Gs4DOPGwRcjsznbKCQjR8LEeqiugcZG6Al4wx89GurGDG5ffDGcdp3ydaNhTJ1jedRPBB2ACfUwYgQ0NECvz6IYORImTIARI+HCBsfaqM3BIIh0LnEUOKqqb7vbG3CEYirgWRNNwDYRWaiqH8ede7Vvuwl4A1gMzBeRQ24Z6kXkDVW9GjguIg2uNdEAfJLdrRnDCU2wGHFFqIJlDyxLeoyIBKYPDMQbBc5lCHgBSlY+EWkBLsP5DQBsFpElqvrfCY5Nai03NMDeP0iWm1GSTM/g2IsD0i+L205mVebQ4kwZo3Ab/iMi4mV7DbBNVetVdYqqTsERhHlxIgHwCnCtiIx1g9jXAq+o6mOq2uieexWwxxUJgI2A1zvqVqA9+9szhgtNTU0cOTLo5Tx69CiNjY2Bx/T19XHy5EnGjRsXeG58Ok4j/xHwf8AYEQnFpSfjRuAtVT2tqqeBl4FFiQ5U1cdVtVVVWydMmJDy3g0j36Tb6+lO4GkR2Q5cDvwo6EARaRWRJwBU9TOcWMQ77ufv3LRk3A8sE5G9OD2q7k+zjMYwZsGCBezdu5eDBw/S09PD+vXraWtrizmmra2NdeucfhIbNmxg6dKliAhtbW2sX7+e7u5uDh48yN69e1m4cGH0mkCV26tpJbBRHRPkdcDr1ZTOC81h4KsiEhKRME4gOyvXk2EUHFU97z/z589Xw3jxxRf1kksu0ebmZl27dq2qqt53333a3t6uqqpnz57VFStW6LRp03TBggW6f//+6Llr167V5uZmnT59ur700ksx1wS6gP3AverWOZxOHluAfcC/AxE3fQGOhd0JfArsdNMrgX/GEYddwENqddsoMsBWTaMeiibwz55vtLa26tatW4tdDKNMEZF3VbW1GHlb3TbySbp126bwMAzDMJJiQmEYhmEkxYTCMAzDSIoJhWEYhpGUsghmi8gJ4H8Ddo/H6fdeClhZElPqZblYVYsyoMHqdsaUSjng/ChLWnW7LIQiGSKytVg9VuKxsiTGypIdpVTWUilLqZQDyqss5noyDMMwkmJCYRiGYSRlOAjF48UugA8rS2KsLNlRSmUtlbKUSjmgjMpS9jEKwzAMY2gMB4vCMAzDGAImFIZhGEZSylYoROQ6EflQRPaJyOoC5z1JRF4Xkd0islNEvuOmrxGRDhF5z/0sL1B5DonIB26eW920cSKyWUT2un/HFqAcM3z3/p6InBKR7xbquYjIUyLyiYjs8KUlfA7i8Khbf7aLyLx8lCkbrG7HlMfqNgWo2+lMMXu+fXCmdN6PMxV0FfA+MLOA+TfgLOQEUAvsAWbirAx4dxGexyFgfFzaA8Bq9/tq4CdF+B99jLOWV0GeC87yvfOAHameA7AcZ3EhwVlg6O1C/9+SPDer24Plsbqt+a/b5WpRLAT2qeoBVe0B1gM3FCpzVT2mqtvc71/irEGQdE3lInADsM79vg74WoHzvwbYr6pBo45zjjrLjsYvnBX0HG4A/kUd3sJZ0a6hMCVNitXt1FjddshZ3S5XobgI8K9heZQiVWYRmQLMBbw1x1e55t5ThTCJXRT4tYi8K856zAATVfUYOD9+oL5AZfFYCTzj2y7Gc4Hg51AydSiOkimX1e1Ayq5ul6tQSIK0gvcDFpFRwK+A76rqKeAxYBrOcrLHgAcLVJQrVXUecD1wh4gsKVC+CRFnWdE2nJXhoHjPJRklUYcSUBLlsrqdmHKt2+UqFEeBSb7tJuCjQhZAnHWRfwU8rarPA6jqcVXtV9UB4Oc4boS8o6ofuX8/AV5w8z3umZvu308KURaX64FtqnrcLVdRnotL0HMoeh0KoOjlsrqdlLKs2+UqFO8Al4jIVFfhVwIbC5W5iAjwJLBbVR/ypfv9gDcCO+LPzUNZRopIrfcduNbNdyNwq3vYrUB7vsvi4xv4TPNiPBcfQc9hI3CL20NkEXDSM+OLjNXtwTytbicnd3W7kL0BCvnBiezvwekhcm+B874Kx5TbDrznfpYD/wp84KZvBBoKUJZmnJ4x7wM7vWcBXAC8Cux1/44r0LMZAXwK1PnSCvJccH7Ax4BenLeq24KeA455/g9u/fkAaC1kHUpxH1a31ep2XN55rds2hYdhGIaRlHJ1PRmGYRg5woTCMAzDSIoJhWEYhpEUEwrDMAwjKSYUhmEYRlJMKAzDMIykmFAYhmEYSfl/0qXCva9X4FsAAAAASUVORK5CYII=\n",
      "text/plain": [
       "<Figure size 432x288 with 2 Axes>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "# import pickle\n",
    "\n",
    "# with open('stats.st', 'rb') as statfile:\n",
    "#     statistic = pickle.load(statfile)\n",
    "    \n",
    "# #print(statistic)\n",
    "\n",
    "# #trainer.plot_over_epoch()\n",
    "# from trainer import VQATrainer\n",
    "\n",
    "# trainer = VQATrainer(None, None)\n",
    "# trainer.statistics = statistic\n",
    "\n",
    "trainer.plot_over_epoch()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2018-07-11T14:54:54.683210Z",
     "start_time": "2018-07-11T14:54:54.676464Z"
    }
   },
   "outputs": [
    {
     "ename": "SyntaxError",
     "evalue": "invalid syntax (<ipython-input-9-a5cb0d8dbd9c>, line 5)",
     "output_type": "error",
     "traceback": [
      "\u001b[0;36m  File \u001b[0;32m\"<ipython-input-9-a5cb0d8dbd9c>\"\u001b[0;36m, line \u001b[0;32m5\u001b[0m\n\u001b[0;31m    for idx in range(8):[random.randint(0, 8) for i in range(8)]:\u001b[0m\n\u001b[0m                                                                 ^\u001b[0m\n\u001b[0;31mSyntaxError\u001b[0m\u001b[0;31m:\u001b[0m invalid syntax\n"
     ]
    }
   ],
   "source": [
    "from torchvision import transforms\n",
    "import matplotlib.pyplot as plt\n",
    "import random\n",
    "\n",
    "for idx in range(8):[random.randint(0, 8) for i in range(8)]:\n",
    "    print('\\nqn no', idx)\n",
    "    qns, img, ans = collate([train_dataset[idx]])\n",
    "    output = model(img.cuda(), qns.long().cuda())\n",
    "    _, pred = output.topk(10)\n",
    "    # print(qns, pred)\n",
    "\n",
    "    #pil_img = transforms.ToPILImage()(img)\n",
    "    #plt.imshow(pil_img)\n",
    "    qnss = ' '.join([vocab.idx2word[i.item()] for i in qns.data])\n",
    "    ans = ' / '.join([answers.idx2ans[j.item()] for j in pred[0]])\n",
    "    print('question:', qnss)\n",
    "    print('answer:', ans)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:AI_Proj]",
   "language": "python",
   "name": "conda-env-AI_Proj-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.5"
  },
  "toc": {
   "base_numbering": 1,
   "nav_menu": {},
   "number_sections": false,
   "sideBar": true,
   "skip_h1_title": false,
   "title_cell": "Table of Contents",
   "title_sidebar": "Contents",
   "toc_cell": false,
   "toc_position": {},
   "toc_section_display": true,
   "toc_window_display": false
  },
  "varInspector": {
   "cols": {
    "lenName": 16,
    "lenType": 16,
    "lenVar": 40
   },
   "kernels_config": {
    "python": {
     "delete_cmd_postfix": "",
     "delete_cmd_prefix": "del ",
     "library": "var_list.py",
     "varRefreshCmd": "print(var_dic_list())"
    },
    "r": {
     "delete_cmd_postfix": ") ",
     "delete_cmd_prefix": "rm(",
     "library": "var_list.r",
     "varRefreshCmd": "cat(var_dic_list()) "
    }
   },
   "types_to_exclude": [
    "module",
    "function",
    "builtin_function_or_method",
    "instance",
    "_Feature"
   ],
   "window_display": false
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
